CREATE TABLE [staging].[curves] (
    [ID]                   NVARCHAR (255) NULL,
    [WEEK]                 FLOAT (53)     NULL,
    [Call_P]               FLOAT (53)     NULL,
    [Click_P]              FLOAT (53)     NULL,
    [F1]                   NVARCHAR (255) NULL,
    [F2]                   NVARCHAR (255) NULL,
    [F3]                   NVARCHAR (255) NULL,
    [Human Understandable] NVARCHAR (255) NULL,
    [F5]                   NVARCHAR (255) NULL,
    [F6]                   NVARCHAR (255) NULL,
    [F7]                   NVARCHAR (255) NULL,
    [F8]                   NVARCHAR (255) NULL,
    [F9]                   NVARCHAR (255) NULL,
    [F10]                  NVARCHAR (255) NULL,
    [F11]                  NVARCHAR (255) NULL,
    [F12]                  NVARCHAR (255) NULL,
    [Machine ID]           FLOAT (53)     NULL,
    [F14]                  FLOAT (53)     NULL,
    [F15]                  FLOAT (53)     NULL,
    [F16]                  FLOAT (53)     NULL,
    [F17]                  FLOAT (53)     NULL,
    [F18]                  FLOAT (53)     NULL,
    [F19]                  FLOAT (53)     NULL,
    [F20]                  FLOAT (53)     NULL
);

