CREATE TABLE [staging].[WB_00_UVAQ_Conversion_Rates] (
    [Conv_Rate_ID]              CHAR (255) NOT NULL,
    [crw_STRAT_call_conv_rate]  FLOAT (53) NULL,
    [crw_STRAT_click_conv_rate] FLOAT (53) NULL,
    [crw_UVRS_call_conv_rate]   FLOAT (53) NULL,
    [crw_UVRS_click_conv_rate]  FLOAT (53) NULL,
    [crw_HSIA_call_conv_rate]   FLOAT (53) NULL,
    [crw_HSIA_click_conv_rate]  FLOAT (53) NULL,
    [crw_DSL_call_conv_rate]    FLOAT (53) NULL,
    [crw_DSL_click_conv_rate]   FLOAT (53) NULL,
    [crw_DSLD_call_conv_rate]   FLOAT (53) NULL,
    [crw_DSLD_click_conv_rate]  FLOAT (53) NULL,
    [crw_ACCL_call_conv_rate]   FLOAT (53) NULL,
    [crw_ACCL_click_conv_rate]  FLOAT (53) NULL,
    [crw_WLV_call_conv_rate]    FLOAT (53) NULL,
    [crw_WLV_click_conv_rate]   FLOAT (53) NULL,
    [crw_VOIP_call_conv_rate]   FLOAT (53) NULL,
    [crw_VOIP_click_conv_rate]  FLOAT (53) NULL,
    [crw_DISH_call_conv_rate]   FLOAT (53) NULL,
    [crw_DISH_click_conv_rate]  FLOAT (53) NULL,
    [crw_WLF_call_conv_rate]    FLOAT (53) NULL,
    [crw_WLF_click_conv_rate]   FLOAT (53) NULL,
    [crw_WLD_call_conv_rate]    FLOAT (53) NULL,
    [crw_WLD_click_conv_rate]   FLOAT (53) NULL,
    [crw_IPDSL_call_conv_rate]  FLOAT (53) NULL,
    [crw_IPDSL_click_conv_rate] FLOAT (53) NULL
);

