CREATE TABLE [mailfiles].[Input_Feb_EM] (
    [acct_id]                       VARCHAR (12)  NULL,
    [cust_loc_id]                   BIGINT        NULL,
    [blng_addr_loc_src_addr_key_id] VARCHAR (13)  NULL,
    [acct_nbr]                      VARCHAR (13)  NULL,
    [contct_phon_nbr]               VARCHAR (10)  NULL,
    [bill_sys_geo_id]               VARCHAR (2)   NULL,
    [UV_Mobile_Phone_Nbr]           VARCHAR (10)  NULL,
    [srv_accs_id]                   VARCHAR (9)   NULL,
    [blng_full_nm]                  VARCHAR (77)  NULL,
    [blng_nm_prfx_txt]              VARCHAR (5)   NULL,
    [blng_frst_nm]                  VARCHAR (27)  NULL,
    [blng_mid_initial_txt]          VARCHAR (4)   NULL,
    [blng_lst_nm]                   VARCHAR (29)  NULL,
    [blng_nm_sufx_txt]              VARCHAR (2)   NULL,
    [addr_ln_1_txt]                 VARCHAR (100) NULL,
    [addr_ln_2_txt]                 VARCHAR (30)  NULL,
    [addr_ln_3_txt]                 VARCHAR (26)  NULL,
    [cty_nm]                        VARCHAR (22)  NULL,
    [st_cd]                         VARCHAR (2)   NULL,
    [zipcd]                         VARCHAR (5)   NULL,
    [zipcd_plus]                    VARCHAR (4)   NULL,
    [wirlne_rgn_geo_cd]             VARCHAR (2)   NULL,
    [CreativeCode]                  VARCHAR (1)   NULL,
    [TreatmentCode]                 VARCHAR (9)   NULL,
    [CAMPAIGNCODE]                  VARCHAR (12)  NULL,
    [CELLCODE]                      VARCHAR (10)  NULL,
    [OFFERCODE1]                    VARCHAR (9)   NULL,
    [ovals_lvng_unit_id]            VARCHAR (12)  NULL,
    [dstrb_area_cd]                 VARCHAR (6)   NULL,
    [clli_8_cd]                     VARCHAR (8)   NULL,
    [dsgnt_mkt_area_cd]             VARCHAR (3)   NULL,
    [uvrs_availty_dt]               DATETIME      NULL,
    [telco_subsrptn_sts_cd]         VARCHAR (1)   NULL,
    [wirls_subsrptn_sts_cd]         VARCHAR (1)   NULL,
    [telco_brdbnd_subsrptn_sts_cd]  VARCHAR (1)   NULL,
    [DSL_dryloop_indicator]         VARCHAR (1)   NULL,
    [DF_Blng_Addr_vs_Srv_Addr]      VARCHAR (7)   NULL,
    [service addr_In_1_txt]         VARCHAR (52)  NULL,
    [service addr_In_2_txt]         VARCHAR (1)   NULL,
    [service addr_In_3_txt]         VARCHAR (1)   NULL,
    [service cty_nm]                VARCHAR (22)  NULL,
    [service st_cd]                 VARCHAR (2)   NULL,
    [service zipcd]                 VARCHAR (5)   NULL,
    [DF_AGING]                      VARCHAR (1)   NULL,
    [cpni_ind]                      VARCHAR (1)   NULL,
    [srcsrc_cust_loc_id]            BIGINT        NULL,
    [brdbnd_mx_speed_cd]            VARCHAR (6)   NULL,
    [pair_bonding]                  VARCHAR (1)   NULL,
    [wireless_prescreen]            VARCHAR (1)   NULL,
    [DF_CLOC_MODEL_1200_decimal]    VARCHAR (9)   NULL,
    [Wireline_U300_MODEL_719]       VARCHAR (1)   NULL,
    [Wireline_U300_MODEL_494]       VARCHAR (1)   NULL,
    [Wireline_U300_MODEL_694]       VARCHAR (1)   NULL,
    [Wireline_U300_MODEL_693]       VARCHAR (1)   NULL,
    [Wireline_U300_MODEL_695]       VARCHAR (1)   NULL,
    [Wireline_U200_MODEL_718]       VARCHAR (1)   NULL,
    [Wireline_U200_MODEL_493]       VARCHAR (1)   NULL,
    [Wireline_U200_MODEL_691]       VARCHAR (1)   NULL,
    [Wireline_U200_MODEL_690]       VARCHAR (1)   NULL,
    [Wireline_U200_MODEL_692]       VARCHAR (1)   NULL,
    [DF_CLOC_MODEL_637]             VARCHAR (1)   NULL,
    [DF_CLOC_MODEL_638]             VARCHAR (1)   NULL,
    [DF_CLOC_MODEL_639]             VARCHAR (1)   NULL,
    [DF_CLOC_MODEL_449]             VARCHAR (1)   NULL,
    [DF_CLOC_MODEL_708]             VARCHAR (1)   NULL,
    [uverse_prescreen]              VARCHAR (1)   NULL,
    [cnxns_sgmnt_cd]                VARCHAR (1)   NULL,
    [cbsa_cd]                       VARCHAR (6)   NULL,
    [cbsa_nm]                       VARCHAR (1)   NULL,
    [purchase_channel_wls]          VARCHAR (1)   NULL,
    [purchase_channel_telco]        VARCHAR (1)   NULL,
    [purchase_channel_dsl]          VARCHAR (1)   NULL,
    [control_vs_mail]               VARCHAR (1)   NULL,
    [ent_acct_lang_cd]              VARCHAR (2)   NULL,
    [ent_blng_lang_nm]              VARCHAR (7)   NULL,
    [indiv_respons_unit]            VARCHAR (3)   NULL,
    [fan]                           VARCHAR (8)   NULL,
    [email]                         VARCHAR (1)   NULL,
    [billing_smart_phone_flag]      VARCHAR (1)   NULL,
    [G_flag]                        VARCHAR (2)   NULL,
    [field_81]                      VARCHAR (1)   NULL,
    [brdbnd_speed_cd]               VARCHAR (1)   NULL,
    [field_83]                      VARCHAR (1)   NULL,
    [field_84]                      VARCHAR (1)   NULL,
    [field_85]                      VARCHAR (1)   NULL,
    [field_86]                      VARCHAR (1)   NULL,
    [field_87]                      VARCHAR (1)   NULL
);

