ALTER VIEW
bvt_prod.CLM_Revenue_GRE_Raw_Data

AS


Select Project_ID, ParentID, 
CASE WHEN Project_ID IN (1458469,1488135,1458471) THEN Project_ID 
WHEN a.media_code = 'BI' THEN ParentID ELSE Project_ID END AS Lookup_Value,
 CASE WHEN a.media_code = 'FYI' THEN 'BM' ELSE a.Media_Code END AS Media, Start_Date, 
CASE WHEN End_Date_Traditional <= (Select b.End_Date from JAVDB.IREPORT_2015.dbo.wb_00_reporting_cycle a
JOIN JAVDB.IREPORT.dbo.WB_00_Media_Calendar_Weekly b
on a.ReportCycle_YYYYWW = b.ReportWeek_YYYYWW) THEN 'Completed' ELSE 'Tracking' END AS Tracking_Completed,
Month(Start_Date) as Start_Month, YEAR(Start_Date) as Start_Year,
eCRW_Project_Name, Campaign_Name,
SUM(ISNULL(ITP_Budget,0)) as Budget, SUM(ISNULL(Goal_ITP_Dir_Calls,0)) AS Goal_Calls,
SUM(ISNULL(Goal_ITP_Dir_Clicks,0)) AS Goal_Clicks,
SUM(ISNULL(ITP_Quantity_UnApp,0)) AS Volume, SUM(ISNULL(ITP_Dir_Calls,0)) as Calls,
SUM(ISNULL(ITP_Dir_Clicks,0)) AS Clicks, SUM(ISNULL(ITP_Dir_QRScans,0)) as QR_Scans,
SUM(ISNULL(ITP_Unique_Opens,0)) AS Opens,
SUM(ISNULL(ITP_Dir_Sales_TS_CING_VOICE_N, 0)+
ISNULL(ITP_Dir_Sales_TS_CING_DATA_N, 0)+
ISNULL(ITP_Dir_Sales_TS_CING_WHP_N, 0)+
ISNULL(ITP_Dir_Sales_TS_DISH_N, 0)+
ISNULL(ITP_Dir_Sales_TS_DSL_REG_N, 0)+
ISNULL(ITP_Dir_Sales_TS_DSL_DRY_N, 0)+
ISNULL(ITP_Dir_Sales_TS_DLIFE_N, 0)+
ISNULL(ITP_Dir_Sales_TS_DSL_IP_N, 0)+
ISNULL(ITP_Dir_Sales_TS_UVRS_HSIA_N, 0)+
ISNULL(ITP_Dir_Sales_TS_UVRS_HSIAG_N, 0)+
ISNULL(ITP_Dir_Sales_TS_UVRS_TV_N, 0)+
ISNULL(ITP_Dir_Sales_TS_LOCAL_ACCL_N, 0)+
ISNULL(ITP_Dir_Sales_TS_UVRS_VOIP_N, 0)) as Strat_Call_Sales,
SUM(ISNULL(ITP_Dir_Sales_ON_CING_VOICE_N, 0)+
ISNULL(ITP_Dir_Sales_ON_CING_DATA_N, 0)+
ISNULL(ITP_Dir_Sales_ON_CING_WHP_N, 0)+
ISNULL(ITP_Dir_Sales_ON_DISH_N, 0)+
ISNULL(ITP_Dir_Sales_ON_DSL_REG_N, 0)+
ISNULL(ITP_Dir_Sales_ON_DSL_DRY_N, 0)+
ISNULL(ITP_Dir_Sales_ON_DLIFE_N, 0)+
ISNULL(ITP_Dir_Sales_ON_DSL_IP_N, 0)+
ISNULL(ITP_Dir_Sales_ON_UVRS_HSIA_N, 0)+
ISNULL(ITP_Dir_Sales_ON_UVRS_HSIAG_N, 0)+
ISNULL(ITP_Dir_Sales_ON_UVRS_TV_N, 0)+
ISNULL(ITP_Dir_Sales_ON_LOCAL_ACCL_N, 0)+
ISNULL(ITP_Dir_Sales_ON_UVRS_VOIP_N, 0)) as Strat_Online_Sales,
SUM(ISNULL(ITP_Dir_Sales_TS_CING_VOICE_N, 0)+
ISNULL(ITP_Dir_Sales_TS_CING_DATA_N, 0)+
ISNULL(ITP_Dir_Sales_TS_CING_WHP_N, 0)+
ISNULL(ITP_Dir_Sales_TS_DISH_N, 0)+
ISNULL(ITP_Dir_Sales_TS_DSL_REG_N, 0)+
ISNULL(ITP_Dir_Sales_TS_DSL_DRY_N, 0)+
ISNULL(ITP_Dir_Sales_TS_DLIFE_N, 0)+
ISNULL(ITP_Dir_Sales_TS_DSL_IP_N, 0)+
ISNULL(ITP_Dir_Sales_TS_UVRS_HSIA_N, 0)+
ISNULL(ITP_Dir_Sales_TS_UVRS_HSIAG_N, 0)+
ISNULL(ITP_Dir_Sales_TS_UVRS_TV_N, 0)+
ISNULL(ITP_Dir_Sales_TS_LOCAL_ACCL_N, 0)+
ISNULL(ITP_Dir_Sales_TS_UVRS_VOIP_N, 0)+
ISNULL(ITP_Dir_Sales_TS_UVRS_BOLT_N, 0)+
ISNULL(ITP_Dir_Sales_TS_DSL_REG_U, 0)+
ISNULL(ITP_Dir_Sales_TS_DSL_DRY_U, 0)+
ISNULL(ITP_Dir_Sales_TS_DSL_IP_U, 0)+
ISNULL(ITP_Dir_Sales_TS_UVRS_HSIA_U, 0)+
ISNULL(ITP_Dir_Sales_TS_UVRS_TV_U, 0)+
ISNULL(ITP_Dir_Sales_TS_CING_VOICE_U,0)+
ISNULL(ITP_Dir_Sales_TS_CING_DATA_U,0)+
ISNULL(ITP_Dir_Sales_TS_DISH_U,0)+
ISNULL(ITP_Dir_Sales_TS_UVRS_BOLT_U,0)+
ISNULL(ITP_Dir_Sales_TS_LOCAL_ACCL_U,0)+
ISNULL(ITP_Dir_Sales_TS_UVRS_VOIP_U,0)) AS Total_Call_Sales,
SUM(ISNULL(ITP_Dir_Sales_ON_CING_VOICE_N, 0)+
ISNULL(ITP_Dir_Sales_ON_CING_DATA_N, 0)+
ISNULL(ITP_Dir_Sales_ON_CING_WHP_N, 0)+
ISNULL(ITP_Dir_Sales_ON_DISH_N, 0)+
ISNULL(ITP_Dir_Sales_ON_DSL_REG_N, 0)+
ISNULL(ITP_Dir_Sales_ON_DSL_DRY_N, 0)+
ISNULL(ITP_Dir_Sales_ON_DLIFE_N, 0)+
ISNULL(ITP_Dir_Sales_ON_DSL_IP_N, 0)+
ISNULL(ITP_Dir_Sales_ON_UVRS_HSIA_N, 0)+
ISNULL(ITP_Dir_Sales_ON_UVRS_HSIAG_N, 0)+
ISNULL(ITP_Dir_Sales_ON_UVRS_TV_N, 0)+
ISNULL(ITP_Dir_Sales_ON_LOCAL_ACCL_N, 0)+
ISNULL(ITP_Dir_Sales_ON_UVRS_VOIP_N, 0)+
ISNULL(ITP_Dir_Sales_ON_UVRS_BOLT_N, 0)+
ISNULL(ITP_Dir_Sales_ON_DSL_REG_U, 0)+
ISNULL(ITP_Dir_Sales_ON_DSL_DRY_U, 0)+
ISNULL(ITP_Dir_Sales_ON_DSL_IP_U, 0)+
ISNULL(ITP_Dir_Sales_ON_UVRS_HSIA_U, 0)+
ISNULL(ITP_Dir_Sales_ON_UVRS_TV_U, 0)+
ISNULL(ITP_Dir_Sales_ON_CING_VOICE_U,0)+
ISNULL(ITP_Dir_Sales_ON_CING_DATA_U,0)+
ISNULL(ITP_Dir_Sales_ON_DISH_U,0)+
ISNULL(ITP_Dir_Sales_ON_UVRS_BOLT_U,0)+
ISNULL(ITP_Dir_Sales_ON_LOCAL_ACCL_U,0)+
ISNULL(ITP_Dir_Sales_ON_UVRS_VOIP_U,0)) AS Total_Online_Sales,
sum(
ISNULL(LTV_ITP_TS_CING_VOICE_N, 0)+
ISNULL(LTV_ITP_ON_CING_VOICE_N, 0)+  
ISNULL(LTV_ITP_TS_CING_DATA_N, 0)+
ISNULL(LTV_ITP_ON_CING_DATA_N, 0)+ 
ISNULL(LTV_ITP_TS_CING_WHP_N, 0)+ 
ISNULL(LTV_ITP_ON_CING_WHP_N, 0)+
ISNULL(LTV_ITP_TS_DISH_N, 0)+ 
ISNULL(LTV_ITP_ON_DISH_N, 0)+
ISNULL(LTV_ITP_TS_DSL_REG_N, 0)+ 
ISNULL(LTV_ITP_ON_DSL_REG_N, 0)+  
ISNULL(LTV_ITP_TS_DSL_DRY_N, 0)+ 
ISNULL(LTV_ITP_ON_DSL_DRY_N, 0)+ 
ISNULL(LTV_ITP_TS_DSL_IP_N, 0)+
ISNULL(LTV_ITP_ON_DSL_IP_N, 0)+ 
ISNULL(LTV_ITP_TS_UVRS_HSIA_N, 0)+ 
ISNULL(LTV_ITP_ON_UVRS_HSIA_N, 0)+ 
ISNULL(LTV_ITP_TS_UVRS_HSIAG_N, 0)+ 
ISNULL(LTV_ITP_ON_UVRS_HSIAG_N, 0)+ 
ISNULL(LTV_ITP_TS_UVRS_TV_N, 0)+  
ISNULL(LTV_ITP_ON_UVRS_TV_N, 0)+ 
ISNULL(LTV_ITP_TS_UVRS_BOLT_N, 0)+ 
ISNULL(LTV_ITP_ON_UVRS_BOLT_N, 0)+ 
ISNULL(LTV_ITP_TS_LOCAL_ACCL_N, 0)+ 
ISNULL(LTV_ITP_ON_LOCAL_ACCL_N, 0)+ 
ISNULL(LTV_ITP_TS_UVRS_VOIP_N, 0)+
ISNULL(LTV_ITP_ON_UVRS_VOIP_N, 0)+
ISNULL(LTV_ITP_TS_DLIFE_N, 0)+
ISNULL(LTV_ITP_ON_DLIFE_N, 0)+
ISNULL(LTV_ITP_TS_CING_VOICE_U, 0)+
ISNULL(LTV_ITP_ON_CING_VOICE_U, 0)+ 
ISNULL(LTV_ITP_TS_CING_DATA_U, 0)+
ISNULL(LTV_ITP_ON_CING_DATA_U, 0)+
ISNULL(LTV_ITP_TS_DISH_U, 0)+ 
ISNULL(LTV_ITP_ON_DISH_U, 0)+
ISNULL(LTV_ITP_TS_DSL_REG_U, 0)+ 
ISNULL(LTV_ITP_ON_DSL_REG_U, 0)+ 
ISNULL(LTV_ITP_TS_DSL_DRY_U, 0)+ 
ISNULL(LTV_ITP_ON_DSL_DRY_U, 0)+ 
ISNULL(LTV_ITP_TS_DSL_IP_U, 0)+ 
ISNULL(LTV_ITP_ON_DSL_IP_U, 0)+
ISNULL(LTV_ITP_TS_UVRS_HSIA_U, 0)+ 
ISNULL(LTV_ITP_ON_UVRS_HSIA_U, 0)+ 
ISNULL(LTV_ITP_TS_UVRS_TV_U, 0)+ 
ISNULL(LTV_ITP_ON_UVRS_TV_U, 0)+ 
ISNULL(LTV_ITP_TS_UVRS_BOLT_U, 0)+ 
ISNULL(LTV_ITP_ON_UVRS_BOLT_U, 0)+ 
ISNULL(LTV_ITP_TS_LOCAL_ACCL_U, 0)+ 
ISNULL(LTV_ITP_ON_LOCAL_ACCL_U, 0)+  
ISNULL(LTV_ITP_TS_UVRS_VOIP_U, 0)+
ISNULL(LTV_ITP_ON_UVRS_VOIP_U, 0)) as LTV_ITP_Directed




from (Select a.Project_ID, a.ParentID, Coalesce (a.Tactic_ID, b.tactic_ID, c.ID) as Tactic_ID, a.ExcludeFromScorecard, ReportWeek_YYYYWW, a.End_Date_Traditional, 
a.media_code, a.start_Date,
a.eCRW_Project_Name, a.Campaign_Name,
ITP_Budget, Goal_ITP_Dir_Calls,Goal_ITP_Dir_Clicks, ITP_Quantity_UnApp,ITP_Dir_Calls,
ITP_Dir_Clicks, ITP_Dir_QRScans,ITP_Unique_Opens,
ITP_Dir_Sales_TS_CING_VOICE_N,
ITP_Dir_Sales_TS_CING_DATA_N,
ITP_Dir_Sales_TS_CING_WHP_N,
ITP_Dir_Sales_TS_DISH_N,
ITP_Dir_Sales_TS_DSL_REg_N,
ITP_Dir_Sales_TS_DSL_DRY_N,
ITP_Dir_Sales_TS_DLIFE_N,
ITP_Dir_Sales_TS_DSL_IP_N,
ITP_Dir_Sales_TS_UVRS_HSIA_N,
ITP_Dir_Sales_TS_UVRS_HSIAG_N,
ITP_Dir_Sales_TS_UVRS_TV_N,
ITP_Dir_Sales_TS_LOCAL_ACCL_N,
ITP_Dir_Sales_TS_UVRS_VOIP_N,
ITP_Dir_Sales_TS_UVRS_BOLT_N,
ITP_Dir_Sales_TS_DSL_REG_U,
ITP_Dir_Sales_TS_DSL_DRY_U,
ITP_Dir_Sales_TS_DSL_IP_U,
ITP_Dir_Sales_TS_UVRS_HSIA_U,
ITP_Dir_Sales_TS_UVRS_TV_U,
ITP_Dir_Sales_TS_CING_VOICE_U,
ITP_Dir_Sales_TS_CING_DATA_U,
ITP_Dir_Sales_TS_DISH_U,
ITP_Dir_Sales_TS_UVRS_BOLT_U,
ITP_Dir_Sales_TS_LOCAL_ACCL_U,
ITP_Dir_Sales_TS_UVRS_VOIP_U,
ITP_Dir_Sales_ON_CING_VOICE_N,
ITP_Dir_Sales_ON_CING_DATA_N,
ITP_Dir_Sales_ON_CING_WHP_N,
ITP_Dir_Sales_ON_DISH_N,
ITP_Dir_Sales_ON_DSL_REG_N,
ITP_Dir_Sales_ON_DSL_DRY_N,
ITP_Dir_Sales_ON_DLIFE_N,
ITP_Dir_Sales_ON_DSL_IP_N,
ITP_Dir_Sales_ON_UVRS_HSIA_N,
ITP_Dir_Sales_ON_UVRS_HSIAG_N,
ITP_Dir_Sales_ON_UVRS_TV_N,
ITP_Dir_Sales_ON_LOCAL_ACCL_N,
ITP_Dir_Sales_ON_UVRS_VOIP_N,
ITP_Dir_Sales_ON_UVRS_BOLT_N,
ITP_Dir_Sales_ON_DSL_REG_U,
ITP_Dir_Sales_ON_DSL_DRY_U,
ITP_Dir_Sales_ON_DSL_IP_U,
ITP_Dir_Sales_ON_UVRS_HSIA_U,
ITP_Dir_Sales_ON_UVRS_TV_U,
ITP_Dir_Sales_ON_CING_VOICE_U,
ITP_Dir_Sales_ON_CING_DATA_U,
ITP_Dir_Sales_ON_DISH_U,
ITP_Dir_Sales_ON_UVRS_BOLT_U,
ITP_Dir_Sales_ON_LOCAL_ACCL_U,
ITP_Dir_Sales_ON_UVRS_VOIP_U,
LTV_ITP_TS_CING_VOICE_N ,
LTV_ITP_ON_CING_VOICE_N  ,
LTV_ITP_TS_CING_DATA_N ,
LTV_ITP_ON_CING_DATA_N ,
LTV_ITP_TS_CING_WHP_N  ,
LTV_ITP_ON_CING_WHP_N,
LTV_ITP_TS_DISH_N ,
LTV_ITP_ON_DISH_N,
LTV_ITP_TS_DSL_REG_N, 
LTV_ITP_ON_DSL_REG_N , 
LTV_ITP_TS_DSL_DRY_N ,
LTV_ITP_ON_DSL_DRY_N ,
LTV_ITP_TS_DSL_IP_N ,
LTV_ITP_ON_DSL_IP_N ,
LTV_ITP_TS_UVRS_HSIA_N  ,
LTV_ITP_ON_UVRS_HSIA_N ,
LTV_ITP_TS_UVRS_HSIAG_N ,
LTV_ITP_ON_UVRS_HSIAG_N ,
LTV_ITP_TS_UVRS_TV_N   ,
LTV_ITP_ON_UVRS_TV_N ,
LTV_ITP_TS_UVRS_BOLT_N, 
LTV_ITP_ON_UVRS_BOLT_N ,
LTV_ITP_TS_LOCAL_ACCL_N ,
LTV_ITP_ON_LOCAL_ACCL_N ,
LTV_ITP_TS_UVRS_VOIP_N,
LTV_ITP_ON_UVRS_VOIP_N,
LTV_ITP_TS_DLIFE_N,
LTV_ITP_ON_DLIFE_N,
LTV_ITP_TS_CING_VOICE_U,
LTV_ITP_ON_CING_VOICE_U ,
LTV_ITP_TS_CING_DATA_U ,
LTV_ITP_ON_CING_DATA_U,
LTV_ITP_TS_DISH_U ,
LTV_ITP_ON_DISH_U,
LTV_ITP_TS_DSL_REG_U, 
LTV_ITP_ON_DSL_REG_U ,
LTV_ITP_TS_DSL_DRY_U ,
LTV_ITP_ON_DSL_DRY_U ,
LTV_ITP_TS_DSL_IP_U ,
LTV_ITP_ON_DSL_IP_U,
LTV_ITP_TS_UVRS_HSIA_U, 
LTV_ITP_ON_UVRS_HSIA_U ,
LTV_ITP_TS_UVRS_TV_U ,
LTV_ITP_ON_UVRS_TV_U ,
LTV_ITP_TS_UVRS_BOLT_U, 
LTV_ITP_ON_UVRS_BOLT_U ,
LTV_ITP_TS_LOCAL_ACCL_U ,
LTV_ITP_ON_LOCAL_ACCL_U  ,
LTV_ITP_TS_UVRS_VOIP_U,
LTV_ITP_ON_UVRS_VOIP_U from JAVDB.IREPORT_2015.dbo.IR_Workbook_Data_2017_Cal a
join javdb.ireport_2015.dbo.WB_01_Campaign_List_WB_2017 b
on a.ParentID=b.parentid
join javdb.ireport_2015.dbo.wb_00_reporting_hierarchy_2017 c
 on b.ecrw_att_program_code=c.att_program_code
and b.ecrw_channel_name=c.channel_name
and b.cell_scorecard_group_code_name=c.scorecard_group
UNION

 (Select  Project_ID, ParentID, Tactic_ID,  ExcludeFromScorecard, ReportWeek_YYYYWW, End_Date_Traditional,
media_code, start_Date,
eCRW_Project_Name, Campaign_Name,
ITP_Budget, Goal_ITP_Dir_Calls,Goal_ITP_Dir_Clicks, ITP_Quantity_UnApp,ITP_Dir_Calls,
ITP_Dir_Clicks, ITP_Dir_QRScans,ITP_Unique_Opens,
ITP_Dir_Sales_TS_CING_VOICE_N,
ITP_Dir_Sales_TS_CING_DATA_N,
ITP_Dir_Sales_TS_CING_WHP_N,
ITP_Dir_Sales_TS_DISH_N,
ITP_Dir_Sales_TS_DSL_REg_N,
ITP_Dir_Sales_TS_DSL_DRY_N,
ITP_Dir_Sales_TS_DLIFE_N,
ITP_Dir_Sales_TS_DSL_IP_N,
ITP_Dir_Sales_TS_UVRS_HSIA_N,
ITP_Dir_Sales_TS_UVRS_HSIAG_N,
ITP_Dir_Sales_TS_UVRS_TV_N,
ITP_Dir_Sales_TS_LOCAL_ACCL_N,
ITP_Dir_Sales_TS_UVRS_VOIP_N,
ITP_Dir_Sales_TS_UVRS_BOLT_N,
ITP_Dir_Sales_TS_DSL_REG_U,
ITP_Dir_Sales_TS_DSL_DRY_U,
ITP_Dir_Sales_TS_DSL_IP_U,
ITP_Dir_Sales_TS_UVRS_HSIA_U,
ITP_Dir_Sales_TS_UVRS_TV_U,
ITP_Dir_Sales_TS_CING_VOICE_U,
ITP_Dir_Sales_TS_CING_DATA_U,
ITP_Dir_Sales_TS_DISH_U,
ITP_Dir_Sales_TS_UVRS_BOLT_U,
ITP_Dir_Sales_TS_LOCAL_ACCL_U,
ITP_Dir_Sales_TS_UVRS_VOIP_U,
ITP_Dir_Sales_ON_CING_VOICE_N,
ITP_Dir_Sales_ON_CING_DATA_N,
ITP_Dir_Sales_ON_CING_WHP_N,
ITP_Dir_Sales_ON_DISH_N,
ITP_Dir_Sales_ON_DSL_REG_N,
ITP_Dir_Sales_ON_DSL_DRY_N,
ITP_Dir_Sales_ON_DLIFE_N,
ITP_Dir_Sales_ON_DSL_IP_N,
ITP_Dir_Sales_ON_UVRS_HSIA_N,
ITP_Dir_Sales_ON_UVRS_HSIAG_N,
ITP_Dir_Sales_ON_UVRS_TV_N,
ITP_Dir_Sales_ON_LOCAL_ACCL_N,
ITP_Dir_Sales_ON_UVRS_VOIP_N,
ITP_Dir_Sales_ON_UVRS_BOLT_N,
ITP_Dir_Sales_ON_DSL_REG_U,
ITP_Dir_Sales_ON_DSL_DRY_U,
ITP_Dir_Sales_ON_DSL_IP_U,
ITP_Dir_Sales_ON_UVRS_HSIA_U,
ITP_Dir_Sales_ON_UVRS_TV_U,
ITP_Dir_Sales_ON_CING_VOICE_U,
ITP_Dir_Sales_ON_CING_DATA_U,
ITP_Dir_Sales_ON_DISH_U,
ITP_Dir_Sales_ON_UVRS_BOLT_U,
ITP_Dir_Sales_ON_LOCAL_ACCL_U,
ITP_Dir_Sales_ON_UVRS_VOIP_U,
LTV_ITP_TS_CING_VOICE_N,
LTV_ITP_ON_CING_VOICE_N  ,
LTV_ITP_TS_CING_DATA_N,
LTV_ITP_ON_CING_DATA_N ,
LTV_ITP_TS_CING_WHP_N ,
LTV_ITP_ON_CING_WHP_N,
LTV_ITP_TS_DISH_N ,
LTV_ITP_ON_DISH_N,
LTV_ITP_TS_DSL_REG_N, 
LTV_ITP_ON_DSL_REG_N , 
LTV_ITP_TS_DSL_DRY_N ,
LTV_ITP_ON_DSL_DRY_N ,
LTV_ITP_TS_DSL_IP_N,
LTV_ITP_ON_DSL_IP_N ,
LTV_ITP_TS_UVRS_HSIA_N ,
LTV_ITP_ON_UVRS_HSIA_N ,
LTV_ITP_TS_UVRS_HSIAG_N ,
LTV_ITP_ON_UVRS_HSIAG_N ,
LTV_ITP_TS_UVRS_TV_N  ,
LTV_ITP_ON_UVRS_TV_N ,
LTV_ITP_TS_UVRS_BOLT_N, 
LTV_ITP_ON_UVRS_BOLT_N ,
LTV_ITP_TS_LOCAL_ACCL_N ,
LTV_ITP_ON_LOCAL_ACCL_N ,
LTV_ITP_TS_UVRS_VOIP_N,
LTV_ITP_ON_UVRS_VOIP_N,
LTV_ITP_TS_DLIFE_N,
LTV_ITP_ON_DLIFE_N,
LTV_ITP_TS_CING_VOICE_U,
LTV_ITP_ON_CING_VOICE_U ,
LTV_ITP_TS_CING_DATA_U,
LTV_ITP_ON_CING_DATA_U,
LTV_ITP_TS_DISH_U ,
LTV_ITP_ON_DISH_U,
LTV_ITP_TS_DSL_REG_U, 
LTV_ITP_ON_DSL_REG_U ,
LTV_ITP_TS_DSL_DRY_U ,
LTV_ITP_ON_DSL_DRY_U ,
LTV_ITP_TS_DSL_IP_U ,
LTV_ITP_ON_DSL_IP_U,
LTV_ITP_TS_UVRS_HSIA_U, 
LTV_ITP_ON_UVRS_HSIA_U ,
LTV_ITP_TS_UVRS_TV_U ,
LTV_ITP_ON_UVRS_TV_U ,
LTV_ITP_TS_UVRS_BOLT_U, 
LTV_ITP_ON_UVRS_BOLT_U ,
LTV_ITP_TS_LOCAL_ACCL_U ,
LTV_ITP_ON_LOCAL_ACCL_U  ,
LTV_ITP_TS_UVRS_VOIP_U,
LTV_ITP_ON_UVRS_VOIP_U
from JAVDB.IREPORT_2015.dbo.IR_Workbook_Data_2016_Cal
Where start_date not like '%2017%')) a
JOIN (Select * from JAVDB.IREPORT_2015.dbo.WB_00_Reporting_Hierarchy_2016
UNION Select * From JAVDB.IREPORT_2015.dbo.WB_00_Reporting_Hierarchy_2017) b
on a.Tactic_id = b.ID

Where b.att_program_code = 'UCLM'
And Campaign_Name NOT LIKE '%Best View Objectives%' and Campaign_Name NOT LIKE '%Remaining Data%'
AND ExcludeFromScorecard = 'N'
AND a.Media_Code <> 'Drag'
AND a.ReportWeek_YYYYWW <= (Select ReportCycle_YYYYWW from JAVDB.IREPORT_2015.dbo.wb_00_reporting_cycle_2017)


GROUP BY Project_ID, ParentID, a.media_code, Start_Date, End_Date_Traditional,
Month(Start_Date), YEAR(Start_Date), eCrw_Project_Name, Campaign_Name
