ALTER VIEW
bvt_prod.CLM_Revenue_GRE_Raw_Data

AS


Select Project_ID, ParentID, 
CASE WHEN Project_ID IN (1458469,1488135,1458471) THEN Project_ID 
WHEN a.media_code = 'BI' THEN ParentID ELSE Project_ID END AS Lookup_Value,
 CASE WHEN a.media_code = 'FYI' THEN 'BM' ELSE a.Media_Code END AS Media, Start_Date, 
CASE WHEN End_Date_Traditional <= (Select b.End_Date from JAVDB.IREPORT_2015.dbo.wb_00_reporting_cycle a
JOIN JAVDB.IREPORT.dbo.WB_00_Media_Calendar_Weekly b
on a.ReportCycle_YYYYWW = b.ReportWeek_YYYYWW) THEN 'Completed' ELSE 'Tracking' END AS Tracking_Completed,
Month(Start_Date) as Start_Month, YEAR(Start_Date) as Start_Year,
eCRW_Project_Name, Campaign_Name,
SUM(ISNULL(ITP_Budget,0)) as Budget, SUM(ISNULL(Goal_ITP_Dir_Calls,0)) AS Goal_Calls,
SUM(ISNULL(Goal_ITP_Dir_Clicks,0)) AS Goal_Clicks,
SUM(ISNULL(ITP_Quantity_UnApp,0)) AS Volume, SUM(ISNULL(ITP_Dir_Calls,0)) as Calls,
SUM(ISNULL(ITP_Dir_Clicks,0)) AS Clicks, SUM(ISNULL(ITP_Dir_QRScans,0)) as QR_Scans,
SUM(ISNULL(ITP_Unique_Opens,0)) AS Opens,
SUM(ISNULL(ITP_Dir_Sales_TS_CING_VOICE_N, 0)+
ISNULL(ITP_Dir_Sales_TS_CING_DATA_N, 0)+
ISNULL(ITP_Dir_Sales_TS_CING_WHP_N, 0)+
ISNULL(ITP_Dir_Sales_TS_DISH_N, 0)+
ISNULL(ITP_Dir_Sales_TS_DSL_REG_N, 0)+
ISNULL(ITP_Dir_Sales_TS_DSL_DRY_N, 0)+
ISNULL(ITP_Dir_Sales_TS_DLIFE_N, 0)+
ISNULL(ITP_Dir_Sales_TS_DSL_IP_N, 0)+
ISNULL(ITP_Dir_Sales_TS_UVRS_HSIA_N, 0)+
ISNULL(ITP_Dir_Sales_TS_UVRS_HSIAG_N, 0)+
ISNULL(ITP_Dir_Sales_TS_UVRS_TV_N, 0)+
ISNULL(ITP_Dir_Sales_TS_LOCAL_ACCL_N, 0)+
ISNULL(ITP_Dir_Sales_TS_UVRS_VOIP_N, 0)) as Strat_Call_Sales,
SUM(ISNULL(ITP_Dir_Sales_ON_CING_VOICE_N, 0)+
ISNULL(ITP_Dir_Sales_ON_CING_DATA_N, 0)+
ISNULL(ITP_Dir_Sales_ON_CING_WHP_N, 0)+
ISNULL(ITP_Dir_Sales_ON_DISH_N, 0)+
ISNULL(ITP_Dir_Sales_ON_DSL_REG_N, 0)+
ISNULL(ITP_Dir_Sales_ON_DSL_DRY_N, 0)+
ISNULL(ITP_Dir_Sales_ON_DLIFE_N, 0)+
ISNULL(ITP_Dir_Sales_ON_DSL_IP_N, 0)+
ISNULL(ITP_Dir_Sales_ON_UVRS_HSIA_N, 0)+
ISNULL(ITP_Dir_Sales_ON_UVRS_HSIAG_N, 0)+
ISNULL(ITP_Dir_Sales_ON_UVRS_TV_N, 0)+
ISNULL(ITP_Dir_Sales_ON_LOCAL_ACCL_N, 0)+
ISNULL(ITP_Dir_Sales_ON_UVRS_VOIP_N, 0)) as Strat_Online_Sales,
SUM(ISNULL(ITP_Dir_Sales_TS_CING_VOICE_N, 0)+
ISNULL(ITP_Dir_Sales_TS_CING_DATA_N, 0)+
ISNULL(ITP_Dir_Sales_TS_CING_WHP_N, 0)+
ISNULL(ITP_Dir_Sales_TS_DISH_N, 0)+
ISNULL(ITP_Dir_Sales_TS_DSL_REG_N, 0)+
ISNULL(ITP_Dir_Sales_TS_DSL_DRY_N, 0)+
ISNULL(ITP_Dir_Sales_TS_DLIFE_N, 0)+
ISNULL(ITP_Dir_Sales_TS_DSL_IP_N, 0)+
ISNULL(ITP_Dir_Sales_TS_UVRS_HSIA_N, 0)+
ISNULL(ITP_Dir_Sales_TS_UVRS_HSIAG_N, 0)+
ISNULL(ITP_Dir_Sales_TS_UVRS_TV_N, 0)+
ISNULL(ITP_Dir_Sales_TS_LOCAL_ACCL_N, 0)+
ISNULL(ITP_Dir_Sales_TS_UVRS_VOIP_N, 0)+
ISNULL(ITP_Dir_Sales_TS_UVRS_BOLT_N, 0)+
ISNULL(ITP_Dir_Sales_TS_DSL_REG_U, 0)+
ISNULL(ITP_Dir_Sales_TS_DSL_DRY_U, 0)+
ISNULL(ITP_Dir_Sales_TS_DSL_IP_U, 0)+
ISNULL(ITP_Dir_Sales_TS_UVRS_HSIA_U, 0)+
ISNULL(ITP_Dir_Sales_TS_UVRS_TV_U, 0)+
ISNULL(ITP_Dir_Sales_TS_CING_VOICE_U,0)+
ISNULL(ITP_Dir_Sales_TS_CING_DATA_U,0)+
ISNULL(ITP_Dir_Sales_TS_DISH_U,0)+
ISNULL(ITP_Dir_Sales_TS_UVRS_BOLT_U,0)+
ISNULL(ITP_Dir_Sales_TS_LOCAL_ACCL_U,0)+
ISNULL(ITP_Dir_Sales_TS_UVRS_VOIP_U,0)) AS Total_Call_Sales,
SUM(ISNULL(ITP_Dir_Sales_ON_CING_VOICE_N, 0)+
ISNULL(ITP_Dir_Sales_ON_CING_DATA_N, 0)+
ISNULL(ITP_Dir_Sales_ON_CING_WHP_N, 0)+
ISNULL(ITP_Dir_Sales_ON_DISH_N, 0)+
ISNULL(ITP_Dir_Sales_ON_DSL_REG_N, 0)+
ISNULL(ITP_Dir_Sales_ON_DSL_DRY_N, 0)+
ISNULL(ITP_Dir_Sales_ON_DLIFE_N, 0)+
ISNULL(ITP_Dir_Sales_ON_DSL_IP_N, 0)+
ISNULL(ITP_Dir_Sales_ON_UVRS_HSIA_N, 0)+
ISNULL(ITP_Dir_Sales_ON_UVRS_HSIAG_N, 0)+
ISNULL(ITP_Dir_Sales_ON_UVRS_TV_N, 0)+
ISNULL(ITP_Dir_Sales_ON_LOCAL_ACCL_N, 0)+
ISNULL(ITP_Dir_Sales_ON_UVRS_VOIP_N, 0)+
ISNULL(ITP_Dir_Sales_ON_UVRS_BOLT_N, 0)+
ISNULL(ITP_Dir_Sales_ON_DSL_REG_U, 0)+
ISNULL(ITP_Dir_Sales_ON_DSL_DRY_U, 0)+
ISNULL(ITP_Dir_Sales_ON_DSL_IP_U, 0)+
ISNULL(ITP_Dir_Sales_ON_UVRS_HSIA_U, 0)+
ISNULL(ITP_Dir_Sales_ON_UVRS_TV_U, 0)+
ISNULL(ITP_Dir_Sales_ON_CING_VOICE_U,0)+
ISNULL(ITP_Dir_Sales_ON_CING_DATA_U,0)+
ISNULL(ITP_Dir_Sales_ON_DISH_U,0)+
ISNULL(ITP_Dir_Sales_ON_UVRS_BOLT_U,0)+
ISNULL(ITP_Dir_Sales_ON_LOCAL_ACCL_U,0)+
ISNULL(ITP_Dir_Sales_ON_UVRS_VOIP_U,0)) AS Total_Online_Sales,
sum(
ISNULL(LTV_ITP_TS_CING_VOICE_N, 0)+	
ISNULL(LTV_ITP_ON_CING_VOICE_N, 0)+  
ISNULL(LTV_ITP_TS_CING_DATA_N, 0)+	
ISNULL(LTV_ITP_ON_CING_DATA_N, 0)+ 
ISNULL(LTV_ITP_TS_CING_WHP_N, 0)+ 	
ISNULL(LTV_ITP_ON_CING_WHP_N, 0)+
ISNULL(LTV_ITP_TS_DISH_N, 0)+ 		
ISNULL(LTV_ITP_ON_DISH_N, 0)+
ISNULL(LTV_ITP_TS_DSL_REG_N, 0)+ 		
ISNULL(LTV_ITP_ON_DSL_REG_N, 0)+  
ISNULL(LTV_ITP_TS_DSL_DRY_N, 0)+ 		
ISNULL(LTV_ITP_ON_DSL_DRY_N, 0)+ 
ISNULL(LTV_ITP_TS_DSL_IP_N, 0)+		
ISNULL(LTV_ITP_ON_DSL_IP_N, 0)+ 
ISNULL(LTV_ITP_TS_UVRS_HSIA_N, 0)+ 	
ISNULL(LTV_ITP_ON_UVRS_HSIA_N, 0)+ 
ISNULL(LTV_ITP_TS_UVRS_HSIAG_N, 0)+ 	
ISNULL(LTV_ITP_ON_UVRS_HSIAG_N, 0)+ 
ISNULL(LTV_ITP_TS_UVRS_TV_N, 0)+  	
ISNULL(LTV_ITP_ON_UVRS_TV_N, 0)+ 
ISNULL(LTV_ITP_TS_UVRS_BOLT_N, 0)+ 	
ISNULL(LTV_ITP_ON_UVRS_BOLT_N, 0)+ 
ISNULL(LTV_ITP_TS_LOCAL_ACCL_N, 0)+ 	
ISNULL(LTV_ITP_ON_LOCAL_ACCL_N, 0)+ 
ISNULL(LTV_ITP_TS_UVRS_VOIP_N, 0)+	
ISNULL(LTV_ITP_ON_UVRS_VOIP_N, 0)+
ISNULL(LTV_ITP_TS_DLIFE_N, 0)+	
ISNULL(LTV_ITP_ON_DLIFE_N, 0)+
ISNULL(LTV_ITP_TS_CING_VOICE_U, 0)+	
ISNULL(LTV_ITP_ON_CING_VOICE_U, 0)+ 
ISNULL(LTV_ITP_TS_CING_DATA_U, 0)+	
ISNULL(LTV_ITP_ON_CING_DATA_U, 0)+
ISNULL(LTV_ITP_TS_DISH_U, 0)+ 		
ISNULL(LTV_ITP_ON_DISH_U, 0)+
ISNULL(LTV_ITP_TS_DSL_REG_U, 0)+ 		
ISNULL(LTV_ITP_ON_DSL_REG_U, 0)+ 
ISNULL(LTV_ITP_TS_DSL_DRY_U, 0)+ 		
ISNULL(LTV_ITP_ON_DSL_DRY_U, 0)+ 
ISNULL(LTV_ITP_TS_DSL_IP_U, 0)+ 		
ISNULL(LTV_ITP_ON_DSL_IP_U, 0)+
ISNULL(LTV_ITP_TS_UVRS_HSIA_U, 0)+ 	
ISNULL(LTV_ITP_ON_UVRS_HSIA_U, 0)+ 
ISNULL(LTV_ITP_TS_UVRS_TV_U, 0)+ 		
ISNULL(LTV_ITP_ON_UVRS_TV_U, 0)+ 
ISNULL(LTV_ITP_TS_UVRS_BOLT_U, 0)+ 	
ISNULL(LTV_ITP_ON_UVRS_BOLT_U, 0)+ 
ISNULL(LTV_ITP_TS_LOCAL_ACCL_U, 0)+ 	
ISNULL(LTV_ITP_ON_LOCAL_ACCL_U, 0)+  
ISNULL(LTV_ITP_TS_UVRS_VOIP_U, 0)+	
ISNULL(LTV_ITP_ON_UVRS_VOIP_U, 0)) as LTV_ITP_Directed




from JAVDB.IREPORT_2015.dbo.IR_Workbook_Data_2017 a
JOIN JAVDB.IREPORT_2015.dbo.WB_00_Reporting_Hierarchy_2017 b
on a.Tactic_id = b.ID

Where b.att_program_code = 'UCLM'
And Campaign_Name NOT LIKE '%Best View Objectives%' and Campaign_Name NOT LIKE '%Remaining Data%'
AND ExcludeFromScorecard = 'N'
AND a.Media_Code <> 'Drag'

GROUP BY Project_ID, ParentID, a.media_code, Start_Date, End_Date_Traditional,
Month(Start_Date), YEAR(Start_Date), eCrw_Project_Name, Campaign_Name


