CREATE TABLE [eCRW].[weekly_report_data] (
    [ReportCycle_YYYYWW]           INT           NULL,
    [In-home Month]                INT           NULL,
    [Week In-home]                 INT           NULL,
    [Scorecard Program Channel]    VARCHAR (100) NULL,
    [Program Name]                 VARCHAR (100) NULL,
    [Tactic ID]                    NUMERIC (11)  NULL,
    [AT&T Program Manager]         VARCHAR (255) NULL,
    [Aprimo ID]                    VARCHAR (10)  NULL,
    [Campaign ID]                  NUMERIC (11)  NULL,
    [Campaign Name]                VARCHAR (250) NULL,
    [In-home Date]                 DATETIME      NULL,
    [First Drop Date/ Track Start] DATETIME      NULL,
    [Tracking End Date]            DATETIME      NULL,
    [ParentID]                     NUMERIC (12)  NULL,
    [Cell Title]                   VARCHAR (250) NULL,
    [Channel]                      VARCHAR (50)  NULL,
    [Agency]                       VARCHAR (50)  NULL,
    [eCRW Created Date]            DATETIME      NULL,
    [Call RR]                      FLOAT (53)    NULL,
    [Click RR]                     FLOAT (53)    NULL,
    [TFN]                          VARCHAR (MAX) NULL,
    [TFN Type]                     VARCHAR (50)  NULL,
    [Audience]                     VARCHAR (8)   NOT NULL,
    [URL]                          VARCHAR (MAX) NULL,
    [Quantity]                     NUMERIC (20)  NULL,
    [Budget]                       FLOAT (53)    NULL,
    [TFN Audience]                 VARCHAR (59)  NULL
);

