CREATE TABLE [Commitment_Versions].[CV_2013_February_Submission_Budget_Volume_Calls_Clicks_Sales_v2] (
    [Touch_Type_FK]                      INT          NULL,
    [Audience]                           VARCHAR (8)  NULL,
    [Project]                            VARCHAR (76) NULL,
    [Media_Type]                         VARCHAR (50) NULL,
    [Program_Owner]                      VARCHAR (65) NULL,
    [Media_Week]                         INT          NULL,
    [InHome_Date]                        DATETIME     NULL,
    [CV_Finance_Budget]                  FLOAT (53)   NULL,
    [CV_Project_Budget]                  FLOAT (53)   NULL,
    [CV_Drop_Volume]                     FLOAT (53)   NULL,
    [CV_Calls]                           FLOAT (53)   NULL,
    [CV_Clicks]                          FLOAT (53)   NULL,
    [CV_Call_TV_Sales]                   FLOAT (53)   NULL,
    [CV_Online_TV_Sales]                 FLOAT (53)   NULL,
    [CV_Call_HSIA_Sales]                 FLOAT (53)   NULL,
    [CV_Online_HSIA_Sales]               FLOAT (53)   NULL,
    [CV_Call_VOIP_Sales]                 FLOAT (53)   NULL,
    [CV_Online_VOIP_Sales]               FLOAT (53)   NULL,
    [CV_Call_DSL_Reg_Sales]              FLOAT (53)   NULL,
    [CV_Call_DSL_Dry_Sales]              FLOAT (53)   NULL,
    [CV_Call_Access_Sales]               FLOAT (53)   NULL,
    [CV_Call_Wrls_Voice_Sales]           FLOAT (53)   NULL,
    [CV_Call_Dish_Sales]                 FLOAT (53)   NULL,
    [CV_Call_WRLS_Family_Sales]          FLOAT (53)   NULL,
    [CV_Call_WRLS_Data_Sales]            FLOAT (53)   NULL,
    [CV_Call_IPDSL_Sales]                FLOAT (53)   NULL,
    [CV_Online_DSL_Reg_Sales]            FLOAT (53)   NULL,
    [CV_Online_DSL_Dry_Sales]            FLOAT (53)   NULL,
    [CV_Online_Access_Sales]             FLOAT (53)   NULL,
    [CV_Online_Wrls_Voice_Sales]         FLOAT (53)   NULL,
    [CV_Online_Dish_Sales]               FLOAT (53)   NULL,
    [CV_Online_WRLS_Family_Sales]        FLOAT (53)   NULL,
    [CV_Online_WRLS_Data_Sales]          FLOAT (53)   NULL,
    [CV_Online_IPDSL_Sales]              FLOAT (53)   NULL,
    [CV_Directed_Strategic_Call_Sales]   FLOAT (53)   NULL,
    [CV_Directed_Strategic_Online_Sales] FLOAT (53)   NULL
);

