CREATE TABLE [Forecasting].[UV_Prospect_2014_Actuals_BACKUP] (
    [Month_Long]                      VARCHAR (50) NULL,
    [reportweek_YYYYWW]               NUMERIC (11) NOT NULL,
    [program]                         VARCHAR (15) NOT NULL,
    [media]                           VARCHAR (14) NOT NULL,
    [Actual_Project_Budget]           FLOAT (53)   NULL,
    [Actual_Project_Volume]           FLOAT (53)   NULL,
    [Actual_Calls]                    FLOAT (53)   NULL,
    [Actual_Clicks]                   FLOAT (53)   NULL,
    [Actual_Call_Wrls_Voice_Sales]    FLOAT (53)   NULL,
    [Actual_Call_WRLS_Family_Sales]   FLOAT (53)   NULL,
    [Actual_Call_WRLS_Data_Sales]     FLOAT (53)   NULL,
    [Actual_CALL_Dish_Sales]          FLOAT (53)   NULL,
    [Actual_Call_DSL_Reg_Sales]       FLOAT (53)   NULL,
    [Actual_Call_DSL_Dry_Sales]       FLOAT (53)   NULL,
    [Actual_Call_IPDSL_Sales]         FLOAT (53)   NULL,
    [Actual_Call_HSIA_Sales]          FLOAT (53)   NULL,
    [Actual_Call_TV_Sales]            FLOAT (53)   NULL,
    [Actual_CALL_Access_Sales]        FLOAT (53)   NULL,
    [Actual_Call_VOIP_Sales]          FLOAT (53)   NULL,
    [Actual_ONLINE_Wrls_Voice_Sales]  FLOAT (53)   NULL,
    [Actual_ONLINE_WRLS_Family_Sales] FLOAT (53)   NULL,
    [Actual_ONLINE_WRLS_Data_Sales]   FLOAT (53)   NULL,
    [Actual_ONLINE_Dish_Sales]        FLOAT (53)   NULL,
    [Actual_ONLINE_DSL_Reg_Sales]     FLOAT (53)   NULL,
    [Actual_ONLINE_DSL_Dry_Sales]     FLOAT (53)   NULL,
    [Actual_ONLINE_IPDSL_Sales]       FLOAT (53)   NULL,
    [Actual_ONLINE_HSIA_Sales]        FLOAT (53)   NULL,
    [Actual_ONLINE_TV_Sales]          FLOAT (53)   NULL,
    [Actual_ONLINE_VOIP_Sales]        FLOAT (53)   NULL,
    [Actual_ONLINE_Access_Sales]      FLOAT (53)   NULL
);

