CREATE TABLE [dbo].['Temp 2015 EM Adj$'] (
    [Touch_Type_FK]                      FLOAT (53)     NULL,
    [Audience]                           NVARCHAR (255) NULL,
    [Project]                            NVARCHAR (255) NULL,
    [Media_Type]                         NVARCHAR (255) NULL,
    [Program_Owner]                      NVARCHAR (255) NULL,
    [Media_Week]                         FLOAT (53)     NULL,
    [MediaMonth_Long]                    NVARCHAR (255) NULL,
    [InHome_Date]                        DATETIME       NULL,
    [BV_Finance_Budget]                  FLOAT (53)     NULL,
    [BV_Project_Budget]                  FLOAT (53)     NULL,
    [BV_Drop_Volume]                     FLOAT (53)     NULL,
    [BV_Calls]                           FLOAT (53)     NULL,
    [BV_Clicks]                          FLOAT (53)     NULL,
    [BV_Call_TV_Sales]                   FLOAT (53)     NULL,
    [BV_Online_TV_Sales]                 FLOAT (53)     NULL,
    [BV_Call_HSIA_Sales]                 FLOAT (53)     NULL,
    [BV_Online_HSIA_Sales]               FLOAT (53)     NULL,
    [BV_Call_VOIP_Sales]                 FLOAT (53)     NULL,
    [BV_Online_VOIP_Sales]               FLOAT (53)     NULL,
    [BV_Call_DSL_Reg_Sales]              FLOAT (53)     NULL,
    [BV_Call_DSL_Dry_Sales]              FLOAT (53)     NULL,
    [BV_Call_Access_Sales]               FLOAT (53)     NULL,
    [BV_Call_Wrls_Voice_Sales]           FLOAT (53)     NULL,
    [BV_Call_Dish_Sales]                 FLOAT (53)     NULL,
    [BV_Call_WRLS_Family_Sales]          FLOAT (53)     NULL,
    [BV_Call_WRLS_Data_Sales]            FLOAT (53)     NULL,
    [BV_Call_IPDSL_Sales]                FLOAT (53)     NULL,
    [BV_Online_DSL_Reg_Sales]            FLOAT (53)     NULL,
    [BV_Online_DSL_Dry_Sales]            FLOAT (53)     NULL,
    [BV_Online_Access_Sales]             FLOAT (53)     NULL,
    [BV_Online_Wrls_Voice_Sales]         FLOAT (53)     NULL,
    [BV_Online_Dish_Sales]               FLOAT (53)     NULL,
    [BV_Online_WRLS_Family_Sales]        FLOAT (53)     NULL,
    [BV_Online_WRLS_Data_Sales]          FLOAT (53)     NULL,
    [BV_Online_IPDSL_Sales]              FLOAT (53)     NULL,
    [BV_Directed_Strategic_Call_Sales]   FLOAT (53)     NULL,
    [BV_Directed_Strategic_Online_Sales] FLOAT (53)     NULL
);

