CREATE TABLE [dbo].[OLE DB Destination] (
    [In-Home Media Week]                                 FLOAT (53)     NULL,
    [In-Home Date]                                       DATETIME       NULL,
    [Mail Date]                                          DATETIME       NULL,
    [REC]                                                DATETIME       NULL,
    [Month]                                              BIT            NULL,
    [Campaign Name]                                      NVARCHAR (255) NULL,
    [Channel]                                            NVARCHAR (255) NULL,
    [eCRW Classification]                                DATETIME       NULL,
    [eCRW First Approval Date]                           DATETIME       NULL,
    [Estimated Cost]                                     MONEY          NULL,
    [Estimated Volume]                                   FLOAT (53)     NULL,
    [eCRW Current Cost]                                  MONEY          NULL,
    [eCRW Current Volume]                                FLOAT (53)     NULL,
    [eCRW Agency Final Volume]                           FLOAT (53)     NULL,
    [eCRW Call RR]                                       FLOAT (53)     NULL,
    [Final Volume/Cost Signoff? ]                        MONEY          NULL,
    [eCRW Click RR]                                      FLOAT (53)     NULL,
    [Billed Month: Cost-Agency]                          FLOAT (53)     NULL,
    [Cost-Agency]                                        MONEY          NULL,
    [Billed Month: Cost-Production]                      FLOAT (53)     NULL,
    [Cost-Production]                                    MONEY          NULL,
    [Billed Month: Cost-Postage]                         FLOAT (53)     NULL,
    [Cost-Postage]                                       MONEY          NULL,
    [Billed Month: Cost-Paper]                           MONEY          NULL,
    [Cost-Paper]                                         MONEY          NULL,
    [MCF Refund Received]                                DATETIME       NULL,
    [Committed Call RR]                                  FLOAT (53)     NULL,
    [Committed Click Rate]                               FLOAT (53)     NULL,
    [Committed Volume]                                   FLOAT (53)     NULL,
    [Committed Cost]                                     MONEY          NULL,
    [CV Calls]                                           FLOAT (53)     NULL,
    [CV Clicks]                                          FLOAT (53)     NULL,
    [CV Call Sales]                                      FLOAT (53)     NULL,
    [CV Click Sales]                                     FLOAT (53)     NULL,
    [Agency Classification]                              NVARCHAR (255) NULL,
    [Media Month]                                        FLOAT (53)     NULL,
    [Year]                                               FLOAT (53)     NULL,
    [F38]                                                DATETIME       NULL,
    [F39]                                                DATETIME       NULL,
    [F40]                                                DATETIME       NULL,
    [F41]                                                DATETIME       NULL,
    [Formula for Conditional Formatting in Current Cost] FLOAT (53)     NULL
);

