CREATE TABLE [dbo].[Project_450_Data_20140129] (
    [Product]                    NVARCHAR (255) NULL,
    [Project Year]               FLOAT (53)     NULL,
    [Project Month]              NVARCHAR (255) NULL,
    [Project Name]               NVARCHAR (255) NULL,
    [Project Job Code]           NVARCHAR (255) NULL,
    [Project Cost Status]        NVARCHAR (255) NULL,
    [Tactic]                     NVARCHAR (255) NULL,
    [Format]                     NVARCHAR (255) NULL,
    [Creative Agency]            NVARCHAR (255) NULL,
    [3#0 ACT Total Project Cost] MONEY          NULL,
    [ACT Quantity]               FLOAT (53)     NULL,
    [3#0 ACT Total Project CPP]  MONEY          NULL,
    [3#0 JAN 14 Cost]            MONEY          NULL,
    [3#0 FEB 14 Cost]            NVARCHAR (255) NULL,
    [3#0 MAR 14 Cost]            NVARCHAR (255) NULL,
    [3#0 APR 14 Cost]            NVARCHAR (255) NULL,
    [3#0 MAY 14 Cost]            NVARCHAR (255) NULL,
    [3#0 JUN 14 Cost]            NVARCHAR (255) NULL,
    [3#0 JUL 14 Cost]            NVARCHAR (255) NULL,
    [3#0 AUG 14 Cost]            NVARCHAR (255) NULL,
    [3#0 SEP 14 Cost]            NVARCHAR (255) NULL,
    [3#0 OCT 14 Cost]            NVARCHAR (255) NULL,
    [3#0 NOV 14 Cost]            NVARCHAR (255) NULL,
    [3#0 DEC 14 Cost]            NVARCHAR (255) NULL
);

