CREATE TABLE [CLM].[acct_chnl_usage_summary_minutes] (
    [acct_id]                                            BIGINT NOT NULL,
    [calendar_month]                                     BIGINT NULL,
    [calendar_year]                                      BIGINT NULL,
    [Showtime Too_854]                                   BIGINT NULL,
    [MC Solid Gold Oldies_5124]                          BIGINT NULL,
    [Discovery Familia_3103]                             BIGINT NULL,
    [Disney XD_1304]                                     BIGINT NULL,
    [Showtime Next_864]                                  BIGINT NULL,
    [Sports Alternate 5_695]                             BIGINT NULL,
    [MTV_502]                                            BIGINT NULL,
    [JCTV_570]                                           BIGINT NULL,
    [MoreMAX_835]                                        BIGINT NULL,
    [YES Network_1702]                                   BIGINT NULL,
    [Telehit_3143]                                       BIGINT NULL,
    [NBA League Pass HD 2_2106]                          BIGINT NULL,
    [NULL_886]                                           BIGINT NULL,
    [Telemundo_3007]                                     BIGINT NULL,
    [NHL Center Ice 2_784]                               BIGINT NULL,
    [SportsTime Ohio_735]                                BIGINT NULL,
    [Bandamax_3146]                                      BIGINT NULL,
    [MC 80s_5122]                                        BIGINT NULL,
    [MoreMAX_1834]                                       BIGINT NULL,
    [Disney XD_305]                                      BIGINT NULL,
    [NULL_1095]                                          BIGINT NULL,
    [ESPNEWS_604]                                        BIGINT NULL,
    [MC Soft Rock_5119]                                  BIGINT NULL,
    [TBS_1112]                                           BIGINT NULL,
    [Boomerang en Espanol_3053]                          BIGINT NULL,
    [Style Network_1380]                                 BIGINT NULL,
    [AT&T U-verse Front Row_100]                         BIGINT NULL,
    [AT&T U-verse Movies_945]                            BIGINT NULL,
    [MGM HD_1116]                                        BIGINT NULL,
    [AT&T U-verse Sports_600]                            BIGINT NULL,
    [Smithsonian Channel_1118]                           BIGINT NULL,
    [Encore Family_944]                                  BIGINT NULL,
    [USA Network_125]                                    BIGINT NULL,
    [Cinemax_832]                                        BIGINT NULL,
    [Starz_902]                                          BIGINT NULL,
    [The Church Channel_565]                             BIGINT NULL,
    [NFL Network_630]                                    BIGINT NULL,
    [Local_1051]                                         BIGINT NULL,
    [ATMAX_1846]                                         BIGINT NULL,
    [TBS_113]                                            BIGINT NULL,
    [AT&T Interactive TV App_1423]                       BIGINT NULL,
    [Television Expanola_3029]                           BIGINT NULL,
    [MSG_706]                                            BIGINT NULL,
    [Fox Soccer Channel_1654]                            BIGINT NULL,
    [SOUND_538]                                          BIGINT NULL,
    [mun2_3010]                                          BIGINT NULL,
    [U-verse Showcase_800]                               BIGINT NULL,
    [Food Network _1452]                                 BIGINT NULL,
    [Comcast Sports Network California_768]              BIGINT NULL,
    [Fox Sports Net North_1745]                          BIGINT NULL,
    [Showtime Family Zone_862]                           BIGINT NULL,
    [HBO Comedy_810]                                     BIGINT NULL,
    [YellowPages TV_97]                                  BIGINT NULL,
    [AT&T Account Manager_9910]                          BIGINT NULL,
    [TESTH1_9110]                                        BIGINT NULL,
    [FSN West_772]                                       BIGINT NULL,
    [HBO2_804]                                           BIGINT NULL,
    [BuyIt 2_247]                                        BIGINT NULL,
    [Speed Channel_652]                                  BIGINT NULL,
    [FUEL TV_536]                                        BIGINT NULL,
    [Comcast SportsNet California HD_1767]               BIGINT NULL,
    [ThrillerMAX_1839]                                   BIGINT NULL,
    [H2_1257]                                            BIGINT NULL,
    [Paquete Espanol Multiview_3001]                     BIGINT NULL,
    [Discovery Fit & Health_466]                         BIGINT NULL,
    [We (Womens Entertainment)_373]                      BIGINT NULL,
    [Starz Edge_1904]                                    BIGINT NULL,
    [MC Pop Latino_5143]                                 BIGINT NULL,
    [NULL_793]                                           BIGINT NULL,
    [ESPNU_605]                                          BIGINT NULL,
    [VH1_519]                                            BIGINT NULL,
    [Local_1013]                                         BIGINT NULL,
    [AT&T U-verse Front Row_1000]                        BIGINT NULL,
    [Zee TV_3702]                                        BIGINT NULL,
    [tvMall_471]                                         BIGINT NULL,
    [ActionMAX_836]                                      BIGINT NULL,
    [ESPN2_606]                                          BIGINT NULL,
    [Nickelodeon_314]                                    BIGINT NULL,
    [NULL_3]                                             BIGINT NULL,
    [Cartoon Network_326]                                BIGINT NULL,
    [NULL_9]                                             BIGINT NULL,
    [Comcast Sports Network California_742]              BIGINT NULL,
    [ABC Family Channel_179]                             BIGINT NULL,
    [NULL_6]                                             BIGINT NULL,
    [HD Theater_1102]                                    BIGINT NULL,
    [Encore_932]                                         BIGINT NULL,
    [Cartoon Network_1325]                               BIGINT NULL,
    [Live Multiview Alternate 5_9215]                    BIGINT NULL,
    [truTV_164]                                          BIGINT NULL,
    [5StarMAX_840]                                       BIGINT NULL,
    [ABC News Now_243]                                   BIGINT NULL,
    [Encore Action_938]                                  BIGINT NULL,
    [NULL_636]                                           BIGINT NULL,
    [La Familia Cosmovision_3056]                        BIGINT NULL,
    [NULL_35]                                            BIGINT NULL,
    [NULL_1635]                                          BIGINT NULL,
    [Animal Planet_252]                                  BIGINT NULL,
    [NULL_639]                                           BIGINT NULL,
    [Local_1048]                                         BIGINT NULL,
    [Comedy Central_141]                                 BIGINT NULL,
    [Fox Sports Net South_726]                           BIGINT NULL,
    [Local_1045]                                         BIGINT NULL,
    [NULL_38]                                            BIGINT NULL,
    [Local_1022]                                         BIGINT NULL,
    [Galavision_3003]                                    BIGINT NULL,
    [Comedy Central_1140]                                BIGINT NULL,
    [Univision Deportes_3317]                            BIGINT NULL,
    [Arabic Radio & Television_3732]                     BIGINT NULL,
    [NULL_12]                                            BIGINT NULL,
    [AT&T U-verse Sports_963]                            BIGINT NULL,
    [Local_1042]                                         BIGINT NULL,
    [Outdoor Channel_1680]                               BIGINT NULL,
    [NULL_67]                                            BIGINT NULL,
    [NULL_41]                                            BIGINT NULL,
    [MTV2_1504]                                          BIGINT NULL,
    [NULL_9115]                                          BIGINT NULL,
    [Disney XD en Espanol_3052]                          BIGINT NULL,
    [Local_1016]                                         BIGINT NULL,
    [NULL_64]                                            BIGINT NULL,
    [SportSouth HD_1729]                                 BIGINT NULL,
    [NULL_851]                                           BIGINT NULL,
    [Local_1019]                                         BIGINT NULL,
    [TV Land_1139]                                       BIGINT NULL,
    [V-me_3015]                                          BIGINT NULL,
    [NULL_44]                                            BIGINT NULL,
    [Playboy TV_3952]                                    BIGINT NULL,
    [U-verse Enabled Applications - Set Up Wizard_9301]  BIGINT NULL,
    [Sports Alternate 4_694]                             BIGINT NULL,
    [MC True Country_5130]                               BIGINT NULL,
    [NULL_90]                                            BIGINT NULL,
    [HBO Latino_815]                                     BIGINT NULL,
    [Comcast Sports Network _714]                        BIGINT NULL,
    [HBO Zone_812]                                       BIGINT NULL,
    [FOX Deportes_655]                                   BIGINT NULL,
    [NBA League Pass HD 3_2107]                          BIGINT NULL,
    [HBO Latino_1814]                                    BIGINT NULL,
    [NULL_9373]                                          BIGINT NULL,
    [Lifetime Movie Network_362]                         BIGINT NULL,
    [Halogen HD_1492]                                    BIGINT NULL,
    [PPV_102]                                            BIGINT NULL,
    [Buy TV_228]                                         BIGINT NULL,
    [MC Retro Rock_5113]                                 BIGINT NULL,
    [Encore Love_934]                                    BIGINT NULL,
    [Lifetime Television_1361]                           BIGINT NULL,
    [CNN (Cable News Network)_202]                       BIGINT NULL,
    [NULL_537]                                           BIGINT NULL,
    [Sports Alternate 8_698]                             BIGINT NULL,
    [MC Pop Hits_5120]                                   BIGINT NULL,
    [WGN_1781]                                           BIGINT NULL,
    [Fox Sports Midwest_748]                             BIGINT NULL,
    [qubo_328]                                           BIGINT NULL,
    [WAPA America_3013]                                  BIGINT NULL,
    [NULL_778]                                           BIGINT NULL,
    [NULL_5999]                                          BIGINT NULL,
    [MC Party Favorites_5125]                            BIGINT NULL,
    [MC Mexicana_5145]                                   BIGINT NULL,
    [E! Entertainment Television_134]                    BIGINT NULL,
    [Comcast Sports Network _1771]                       BIGINT NULL,
    [nuvo TV_194]                                        BIGINT NULL,
    [RTR Planeta_3883]                                   BIGINT NULL,
    [Food Network_453]                                   BIGINT NULL,
    [AT&T U-verse Buzz_961]                              BIGINT NULL,
    [LOGO_184]                                           BIGINT NULL,
    [Once Mexico_301]                                    BIGINT NULL,
    [AT&T Pay Per View Schedule_101]                     BIGINT NULL,
    [MC Todays Country_5129]                             BIGINT NULL,
    [Showtime Showcase_856]                              BIGINT NULL,
    [GolTV_3115]                                         BIGINT NULL,
    [QVC_420]                                            BIGINT NULL,
    [The Learning Channel (TLC)_1250]                    BIGINT NULL,
    [EWTN Espanol_3077]                                  BIGINT NULL,
    [NULL_1777]                                          BIGINT NULL,
    [AT&T U-verse Movies_960]                            BIGINT NULL,
    [NULL_9460]                                          BIGINT NULL,
    [Syfy_151]                                           BIGINT NULL,
    [MSG_709]                                            BIGINT NULL,
    [AT&T Kids Multiview_1301]                           BIGINT NULL,
    [NULL_1780]                                          BIGINT NULL,
    [MSG_1708]                                           BIGINT NULL,
    [NHL Center Ice 1_783]                               BIGINT NULL,
    [Fox Sports Detroit_738]                             BIGINT NULL,
    [IFC_797]                                            BIGINT NULL,
    [History Channel_1256]                               BIGINT NULL,
    [Comcast SportsNet California_767]                   BIGINT NULL,
    [Disney Channel_1303]                                BIGINT NULL,
    [NHL Center Ice 4_1786]                              BIGINT NULL,
    [Local_1010]                                         BIGINT NULL,
    [Bravo_182]                                          BIGINT NULL,
    [Fox College Sports - Pacific_649]                   BIGINT NULL,
    [TV Colombia_3026]                                   BIGINT NULL,
    [Local_1033]                                         BIGINT NULL,
    [BIO_1272]                                           BIGINT NULL,
    [Golf Channel_1641]                                  BIGINT NULL,
    [NULL_23]                                            BIGINT NULL,
    [NULL_3014]                                          BIGINT NULL,
    [Local_1007]                                         BIGINT NULL,
    [TNT (Turner Network Television)_109]                BIGINT NULL,
    [Live Multiview Alternate 6_9216]                    BIGINT NULL,
    [Bravo_1181]                                         BIGINT NULL,
    [aapka Colors_3712]                                  BIGINT NULL,
    [VH1_1518]                                           BIGINT NULL,
    [Fox Sports Net Ohio-Cleveland_734]                  BIGINT NULL,
    [Multimedios_3065]                                   BIGINT NULL,
    [AT&T Sports Multiview_1601]                         BIGINT NULL,
    [Fox Sports Florida_721]                             BIGINT NULL,
    [NULL_52]                                            BIGINT NULL,
    [NULL_26]                                            BIGINT NULL,
    [NHL Network_638]                                    BIGINT NULL,
    [CCTV-9_3602]                                        BIGINT NULL,
    [ESPN GamePlan Multiview_4400]                       BIGINT NULL,
    [Fox College Sports - Central_648]                   BIGINT NULL,
    [FSN Prime Ticket_774]                               BIGINT NULL,
    [Live Multiview Alternate 4_9214]                    BIGINT NULL,
    [Jewelry Television_1428]                            BIGINT NULL,
    [FSN Wisconsin HD_1744]                              BIGINT NULL,
    [MTV Tres_506]                                       BIGINT NULL,
    [Fox Sports Southwest - Houston_755]                 BIGINT NULL,
    [Jewelry Television_197]                             BIGINT NULL,
    [Local_1004]                                         BIGINT NULL,
    [NULL_29]                                            BIGINT NULL,
    [Discovery en Espanol_3102]                          BIGINT NULL,
    [NESN_1713]                                          BIGINT NULL,
    [Local_1065]                                         BIGINT NULL,
    [NULL_58]                                            BIGINT NULL,
    [HBO Signature_809]                                  BIGINT NULL,
    [Fox Sports Net Ohio-Cincinnati_732]                 BIGINT NULL,
    [ESPN GamePlan 3_4403]                               BIGINT NULL,
    [NULL_267]                                           BIGINT NULL,
    [Fox Sports Net South_1725]                          BIGINT NULL,
    [NULL_32]                                            BIGINT NULL,
    [HBO (Home Box Office)_1802]                         BIGINT NULL,
    [HBO (Home Box Office)_803]                          BIGINT NULL,
    [HBO Signature_1808]                                 BIGINT NULL,
    [Local_1068]                                         BIGINT NULL,
    [NULL_55]                                            BIGINT NULL,
    [AT&T U-verse Shopping 3_399]                        BIGINT NULL,
    [ESPN_1602]                                          BIGINT NULL,
    [HBO Family_1807]                                    BIGINT NULL,
    [NULL_84]                                            BIGINT NULL,
    [Fox Sports Indiana_749]                             BIGINT NULL,
    [TMC Xtra_884]                                       BIGINT NULL,
    [Customer Notification_962]                          BIGINT NULL,
    [Univision Deportes_3117]                            BIGINT NULL,
    [Whats On Now Multiview_9925]                        BIGINT NULL,
    [INSP (Inspiration Network)_564]                     BIGINT NULL,
    [The Movie Channel (TMC)_1882]                       BIGINT NULL,
    [Starz Movieplex_909]                                BIGINT NULL,
    [VH1 Soul_521]                                       BIGINT NULL,
    [NULL_9370]                                          BIGINT NULL,
    [Local_1039]                                         BIGINT NULL,
    [Local_1036]                                         BIGINT NULL,
    [NULL_87]                                            BIGINT NULL,
    [Spike TV_146]                                       BIGINT NULL,
    [NULL_270]                                           BIGINT NULL,
    [SOAPnet_365]                                        BIGINT NULL,
    [Spike TV_1145]                                      BIGINT NULL,
    [Science Channel_1258]                               BIGINT NULL,
    [Local_1062]                                         BIGINT NULL,
    [NULL_61]                                            BIGINT NULL,
    [MTV Tr3s_3142]                                      BIGINT NULL,
    [The Movie Channel (TMC)_1883]                       BIGINT NULL,
    [MC Hip-Hop and R&B_5102]                            BIGINT NULL,
    [Comcast Sports Network _771]                        BIGINT NULL,
    [ESPN Classic_603]                                   BIGINT NULL,
    [VH1 Classic_520]                                    BIGINT NULL,
    [MC Adult Alternative_5118]                          BIGINT NULL,
    [Starz Comedy_910]                                   BIGINT NULL,
    [MC 70s_5123]                                        BIGINT NULL,
    [The Novelas_191]                                    BIGINT NULL,
    [CMT_1526]                                           BIGINT NULL,
    [Fox Sports Southwest - Houston_1755]                BIGINT NULL,
    [BET (Black Entertainment Television)_156]           BIGINT NULL,
    [ESPN_602]                                           BIGINT NULL,
    [NULL_5380]                                          BIGINT NULL,
    [TBN - Trinity Broadcasting Network_560]             BIGINT NULL,
    [Live Multiview Alternate 3_9213]                    BIGINT NULL,
    [HBO (Home Box Office)_1803]                         BIGINT NULL,
    [Spike TV_1146]                                      BIGINT NULL,
    [World Fishing Network HD_1679]                      BIGINT NULL,
    [Turner Classic Movies (TCM)_1790]                   BIGINT NULL,
    [Viendo Movies_3132]                                 BIGINT NULL,
    [NBA League Pass HD 1_2105]                          BIGINT NULL,
    [CMT (Country Music Television)_1525]                BIGINT NULL,
    [MC Todler Tunes_5128]                               BIGINT NULL,
    [TV Land_138]                                        BIGINT NULL,
    [Great American Country (GAC)_529]                   BIGINT NULL,
    [HBO Comedy_1810]                                    BIGINT NULL,
    [Fox Sports Midwest_1750]                            BIGINT NULL,
    [CNBC World_217]                                     BIGINT NULL,
    [USA Network_124]                                    BIGINT NULL,
    [Local Organization_127]                             BIGINT NULL,
    [CNBC_216]                                           BIGINT NULL,
    [MC Light Classical_5141]                            BIGINT NULL,
    [Customer Notification_2500]                         BIGINT NULL,
    [Local Organization_130]                             BIGINT NULL,
    [History Channel_256]                                BIGINT NULL,
    [Cinemax_1833]                                       BIGINT NULL,
    [NBA League Pass HD 9_2113]                          BIGINT NULL,
    [National Geographic Channel_265]                    BIGINT NULL,
    [Discovery Channel_120]                              BIGINT NULL,
    [AT&T Interactive TV App_423]                        BIGINT NULL,
    [AT&T U-verse Movies_1200]                           BIGINT NULL,
    [SportsNet New York Alternate_705]                   BIGINT NULL,
    [Fox Sports Net South_725]                           BIGINT NULL,
    [V-me Kids_3058]                                     BIGINT NULL,
    [History en Espanol_3104]                            BIGINT NULL,
    [Food Network Application_1457]                      BIGINT NULL,
    [NULL_11]                                            BIGINT NULL,
    [CBTV Michoacan_3067]                                BIGINT NULL,
    [The Learning Channel (TLC)_251]                     BIGINT NULL,
    [NULL_1611]                                          BIGINT NULL,
    [FAITH_580]                                          BIGINT NULL,
    [Showtime Extreme_1859]                              BIGINT NULL,
    [Bravo_181]                                          BIGINT NULL,
    [NULL_14]                                            BIGINT NULL,
    [OuterMAX_844]                                       BIGINT NULL,
    [MC Rap_5105]                                        BIGINT NULL,
    [Sports Alternate 3_1693]                            BIGINT NULL,
    [TV Dominicana_3047]                                 BIGINT NULL,
    [Eternal Word Television Network (EWTN)_562]         BIGINT NULL,
    [NULL_9117]                                          BIGINT NULL,
    [NULL_20]                                            BIGINT NULL,
    [AMC_1795]                                           BIGINT NULL,
    [Local_1050]                                         BIGINT NULL,
    [NULL_43]                                            BIGINT NULL,
    [Sports Alternate 7_1697]                            BIGINT NULL,
    [NULL_17]                                            BIGINT NULL,
    [NBA League Pass HD 6_2110]                          BIGINT NULL,
    [Sportsnet New York_1705]                            BIGINT NULL,
    [AMC_796]                                            BIGINT NULL,
    [Local_1053]                                         BIGINT NULL,
    [NULL_621]                                           BIGINT NULL,
    [Local_1030]                                         BIGINT NULL,
    [Shopping Multiview_412]                             BIGINT NULL,
    [Latinoamerica TV_3046]                              BIGINT NULL,
    [Comcast SportsNet New England HD_1714]              BIGINT NULL,
    [FX Network_128]                                     BIGINT NULL,
    [Local_1027]                                         BIGINT NULL,
    [MTV_1503]                                           BIGINT NULL,
    [MC Easy Listening_5139]                             BIGINT NULL,
    [NULL_49]                                            BIGINT NULL,
    [AT&T U-verse Shopping 4_198]                        BIGINT NULL,
    [Local_1024]                                         BIGINT NULL,
    [FSN Florida HD_1720]                                BIGINT NULL,
    [HBO2_1805]                                          BIGINT NULL,
    [Local_1021]                                         BIGINT NULL,
    [NULL_653]                                           BIGINT NULL,
    [A&E_132]                                            BIGINT NULL,
    [NULL_46]                                            BIGINT NULL,
    [HBO Latino_814]                                     BIGINT NULL,
    [ET-Global_3632]                                     BIGINT NULL,
    [ThrillerMAX_838]                                    BIGINT NULL,
    [DVR Playback Channel_9999]                          BIGINT NULL,
    [Jewelry Television_428]                             BIGINT NULL,
    [NULL_4506]                                          BIGINT NULL,
    [Showtime Women_866]                                 BIGINT NULL,
    [ESPN_611]                                           BIGINT NULL,
    [Amex - Explore Play Learn_297]                      BIGINT NULL,
    [SUR_3111]                                           BIGINT NULL,
    [MC Jazz_5136]                                       BIGINT NULL,
    [Local Organization_9111]                            BIGINT NULL,
    [NBA League Pass HD 10_2114]                         BIGINT NULL,
    [SWRV_1501]                                          BIGINT NULL,
    [NULL_1097]                                          BIGINT NULL,
    [GolTV_1656]                                         BIGINT NULL,
    [BYU_1567]                                           BIGINT NULL,
    [Local_1059]                                         BIGINT NULL,
    [Nat Geo Mundo_3101]                                 BIGINT NULL,
    [Starz_1903]                                         BIGINT NULL,
    [Investigation Discovery_260]                        BIGINT NULL,
    [MLB Network_1634]                                   BIGINT NULL,
    [NULL_107]                                           BIGINT NULL,
    [Showtime Too_855]                                   BIGINT NULL,
    [NULL_1707]                                          BIGINT NULL,
    [SportSouth_1728]                                    BIGINT NULL,
    [Local_1056]                                         BIGINT NULL,
    [NBA TV_1632]                                        BIGINT NULL,
    [Showtime_1853]                                      BIGINT NULL,
    [PBS Kids Sprout_337]                                BIGINT NULL,
    [The Filipino Channel_3682]                          BIGINT NULL,
    [HDNet Movies_1107]                                  BIGINT NULL,
    [Once Mexico_3011]                                   BIGINT NULL,
    [NHL Network_1638]                                   BIGINT NULL,
    [SportSouth_728]                                     BIGINT NULL,
    [MTV Tres_505]                                       BIGINT NULL,
    [Telefe Internacional_3035]                          BIGINT NULL,
    [Local_1003]                                         BIGINT NULL,
    [Military Channel_259]                               BIGINT NULL,
    [Comcast Sports Network California_1742]             BIGINT NULL,
    [FSN Detroit HD_1737]                                BIGINT NULL,
    [NULL_780]                                           BIGINT NULL,
    [AT&T News Multiview_1201]                           BIGINT NULL,
    [MC Tropicales_5144]                                 BIGINT NULL,
    [C-SPAN3_232]                                        BIGINT NULL,
    [The Learning Channel (TLC)_250]                     BIGINT NULL,
    [Music Choice Application_1500]                      BIGINT NULL,
    [AyM Sports_3119]                                    BIGINT NULL,
    [NULL_777]                                           BIGINT NULL,
    [Encore Suspense_936]                                BIGINT NULL,
    [Golf Channel_641]                                   BIGINT NULL,
    [MSG_1709]                                           BIGINT NULL,
    [LOGO_183]                                           BIGINT NULL,
    [Customer Notification_400]                          BIGINT NULL,
    [Travel Channel_1254]                                BIGINT NULL,
    [Nickelodon_1315]                                    BIGINT NULL,
    [NULL_19]                                            BIGINT NULL,
    [MSG_1706]                                           BIGINT NULL,
    [Fox Sports Net Ohio-Cleveland_1734]                 BIGINT NULL,
    [TV Japan_3680]                                      BIGINT NULL,
    [Sports Alternate 2_692]                             BIGINT NULL,
    [NULL_9302]                                          BIGINT NULL,
    [Palladia_1505]                                      BIGINT NULL,
    [ThrillerMAX_839]                                    BIGINT NULL,
    [MC Hit List_5101]                                   BIGINT NULL,
    [NULL_48]                                            BIGINT NULL,
    [Big Ten Network_1650]                               BIGINT NULL,
    [NULL_22]                                            BIGINT NULL,
    [NULL_9102]                                          BIGINT NULL,
    [VH1 Soul_522]                                       BIGINT NULL,
    [FSN Prime Ticket HD_1774]                           BIGINT NULL,
    [MC Dance-Electronica_5104]                          BIGINT NULL,
    [Local_1035]                                         BIGINT NULL,
    [GolTV_3415]                                         BIGINT NULL,
    [cloo_161]                                           BIGINT NULL,
    [NULL_28]                                            BIGINT NULL,
    [Showtime_852]                                       BIGINT NULL,
    [FUNimation Channel HD_1484]                         BIGINT NULL,
    [Sports Alternate 6_696]                             BIGINT NULL,
    [SportsNet New York_704]                             BIGINT NULL,
    [Local_1058]                                         BIGINT NULL,
    [AT&T Sports Multiview_601]                          BIGINT NULL,
    [Univision_3002]                                     BIGINT NULL,
    [HBO Family_807]                                     BIGINT NULL,
    [Sun Sports_723]                                     BIGINT NULL,
    [NULL_25]                                            BIGINT NULL,
    [HBO Zone_813]                                       BIGINT NULL,
    [HBO Zone_1812]                                      BIGINT NULL,
    [Local_1029]                                         BIGINT NULL,
    [MEGA TV_3008]                                       BIGINT NULL,
    [FX Network_1129]                                    BIGINT NULL,
    [NULL_54]                                            BIGINT NULL,
    [HBO (Home Box Office)_802]                          BIGINT NULL,
    [HBO Signature_1809]                                 BIGINT NULL,
    [ESPN_613]                                           BIGINT NULL,
    [Sports Alternate 4_1694]                            BIGINT NULL,
    [NHL Center Ice 4_786]                               BIGINT NULL,
    [NULL_51]                                            BIGINT NULL,
    [NULL_57]                                            BIGINT NULL,
    [Local_1006]                                         BIGINT NULL,
    [Local_1032]                                         BIGINT NULL,
    [Sports Alternate 8_1698]                            BIGINT NULL,
    [Cinemax_1832]                                       BIGINT NULL,
    [CMT (Country Music Television)_525]                 BIGINT NULL,
    [Spike TV_145]                                       BIGINT NULL,
    [NULL_86]                                            BIGINT NULL,
    [PPV_106]                                            BIGINT NULL,
    [Showtime Showcase_857]                              BIGINT NULL,
    [Showtime Showcase_1856]                             BIGINT NULL,
    [Encore Espanol_943]                                 BIGINT NULL,
    [NULL_83]                                            BIGINT NULL,
    [WMAX_842]                                           BIGINT NULL,
    [NHL Center Ice 1_1783]                              BIGINT NULL,
    [CNN (Cable News Network)_1202]                      BIGINT NULL,
    [Centric_515]                                        BIGINT NULL,
    [Fox Sports Net South_1726]                          BIGINT NULL,
    [STAR India PLUS_3706]                               BIGINT NULL,
    [Fox Sports Detroit_1738]                            BIGINT NULL,
    [PEG_99]                                             BIGINT NULL,
    [Comcast SportsNet Chicago_741]                      BIGINT NULL,
    [CMT Pure Country_527]                               BIGINT NULL,
    [MC Alternative_5116]                                BIGINT NULL,
    [Local_1067]                                         BIGINT NULL,
    [Local_1061]                                         BIGINT NULL,
    [Showtime Extreme_858]                               BIGINT NULL,
    [Boomerang_327]                                      BIGINT NULL,
    [ABC Family Channel_1178]                            BIGINT NULL,
    [AT&T Pay Per View Schedule_1101]                    BIGINT NULL,
    [NULL_3312]                                          BIGINT NULL,
    [NULL_89]                                            BIGINT NULL,
    [NULL_298]                                           BIGINT NULL,
    [Local_1064]                                         BIGINT NULL,
    [Syfy_152]                                           BIGINT NULL,
    [Syfy_1151]                                          BIGINT NULL,
    [NBA League Pass HD 5_2109]                          BIGINT NULL,
    [Telefutura_3005]                                    BIGINT NULL,
    [Bloomberg Television_222]                           BIGINT NULL,
    [HBO2_1804]                                          BIGINT NULL,
    [mun2_192]                                           BIGINT NULL,
    [Fox Sports Florida_720]                             BIGINT NULL,
    [Disney Channel_303]                                 BIGINT NULL,
    [VivaTV Plus_3690]                                   BIGINT NULL,
    [Fox Sports Midwest_750]                             BIGINT NULL,
    [ESPN GamePlan 6_4406]                               BIGINT NULL,
    [C-SPAN2_231]                                        BIGINT NULL,
    [ESPNEWS_1604]                                       BIGINT NULL,
    [Teleamazonas Internacional_3041]                    BIGINT NULL,
    [U-verse Showcase_964]                               BIGINT NULL,
    [Style Network_380]                                  BIGINT NULL,
    [HBO Latino_1815]                                    BIGINT NULL,
    [De Pelicula Clasico_3129]                           BIGINT NULL,
    [Cinelatino_3126]                                    BIGINT NULL,
    [NULL_9430]                                          BIGINT NULL,
    [NULL_1166]                                          BIGINT NULL,
    [Nick Jr._320]                                       BIGINT NULL,
    [The Tennis Channel_660]                             BIGINT NULL,
    [The Movie Channel (TMC)_883]                        BIGINT NULL,
    [NULL_33]                                            BIGINT NULL,
    [Sun Sports_1723]                                    BIGINT NULL,
    [IndiePlex_914]                                      BIGINT NULL,
    [Local_1040]                                         BIGINT NULL,
    [ReelzChannel_1799]                                  BIGINT NULL,
    [HBO Family_806]                                     BIGINT NULL,
    [TMC Xtra_1884]                                      BIGINT NULL,
    [ESPN GamePlan 2_4402]                               BIGINT NULL,
    [NULL_637]                                           BIGINT NULL,
    [NULL_30]                                            BIGINT NULL,
    [OWN - Oprah Winfrey Network_170]                    BIGINT NULL,
    [Wealth TV_470]                                      BIGINT NULL,
    [G4_1149]                                            BIGINT NULL,
    [Home Shopping Network (HSN)_422]                    BIGINT NULL,
    [Local_1043]                                         BIGINT NULL,
    [NESN_1712]                                          BIGINT NULL,
    [Fox Sports Florida_1721]                            BIGINT NULL,
    [NULL_9101]                                          BIGINT NULL,
    [MC R&B Soul_5109]                                   BIGINT NULL,
    [Local_1066]                                         BIGINT NULL,
    [NULL_27]                                            BIGINT NULL,
    [Velocity HD_1104]                                   BIGINT NULL,
    [GMA Pinoy_3683]                                     BIGINT NULL,
    [TV5MONDE_3832]                                      BIGINT NULL,
    [Starz Kids & Family_1912]                           BIGINT NULL,
    [Local_1014]                                         BIGINT NULL,
    [E! Entertainment Television_1134]                   BIGINT NULL,
    [Home & Garden Television (HGTV)_451]                BIGINT NULL,
    [NBC Sports Network_640]                             BIGINT NULL,
    [NULL_56]                                            BIGINT NULL,
    [BIO_272]                                            BIGINT NULL,
    [NULL_62]                                            BIGINT NULL,
    [Local_1011]                                         BIGINT NULL,
    [NULL_36]                                            BIGINT NULL,
    [Local_1034]                                         BIGINT NULL,
    [NULL_268]                                           BIGINT NULL,
    [Home & Garden Television (HGTV)_1450]               BIGINT NULL,
    [NULL_59]                                            BIGINT NULL,
    [E! Entertainment Television_135]                    BIGINT NULL,
    [FOX Deportes_3114]                                  BIGINT NULL,
    [NHL Center Ice 5_1787]                              BIGINT NULL,
    [NULL_65]                                            BIGINT NULL,
    [fuse_1535]                                          BIGINT NULL,
    [TeenNick_322]                                       BIGINT NULL,
    [Fox Sports Southwest - San Antonio_756]             BIGINT NULL,
    [NULL_271]                                           BIGINT NULL,
    [FSN Arizona HD_1762]                                BIGINT NULL,
    [NULL_88]                                            BIGINT NULL,
    [Fox Sports Indiana_1749]                            BIGINT NULL,
    [ActionMAX_1837]                                     BIGINT NULL,
    [TV Land_1138]                                       BIGINT NULL,
    [AT&T U-verse Buzz_300]                              BIGINT NULL,
    [MTV Arabia_3738]                                    BIGINT NULL,
    [DIY Network (Do-It-Yourself Network)_1454]          BIGINT NULL,
    [NULL_274]                                           BIGINT NULL,
    [Sports Alternate 1_691]                             BIGINT NULL,
    [Science Channel_258]                                BIGINT NULL,
    [NULL_1270]                                          BIGINT NULL,
    [ESPN GamePlan 4_4404]                               BIGINT NULL,
    [NULL_91]                                            BIGINT NULL,
    [Nick2_316]                                          BIGINT NULL,
    [Cooking Channel_456]                                BIGINT NULL,
    [tvMall_367]                                         BIGINT NULL,
    [NHL Center Ice 3_1785]                              BIGINT NULL,
    [NULL_94]                                            BIGINT NULL,
    [Destination America_465]                            BIGINT NULL,
    [Fox Sports Southwest Alternate_1754]                BIGINT NULL,
    [Lifetime Movie Network_1362]                        BIGINT NULL,
    [GolTV_656]                                          BIGINT NULL,
    [Local_1069]                                         BIGINT NULL,
    [NULL_117]                                           BIGINT NULL,
    [BYU_567]                                            BIGINT NULL,
    [Sun Sports HD_1722]                                 BIGINT NULL,
    [CBS Sports Network_643]                             BIGINT NULL,
    [MSG_708]                                            BIGINT NULL,
    [MC Gospel_5110]                                     BIGINT NULL,
    [MC Metal_5115]                                      BIGINT NULL,
    [C-SPAN_230]                                         BIGINT NULL,
    [TNT (Turner Network Television)_1108]               BIGINT NULL,
    [MLB Network_634]                                    BIGINT NULL,
    [AT&T U-verse Call History_9900]                     BIGINT NULL,
    [Fox Movie Channel_792]                              BIGINT NULL,
    [MSNBC_1215]                                         BIGINT NULL,
    [HBO Signature_808]                                  BIGINT NULL,
    [Crime & Investigation Network_163]                  BIGINT NULL,
    [Sundance Channel_798]                               BIGINT NULL,
    [SWRV_5100]                                          BIGINT NULL,
    [NULL_1778]                                          BIGINT NULL,
    [New England Sports Network_713]                     BIGINT NULL,
    [NULL_779]                                           BIGINT NULL,
    [WGN America_180]                                    BIGINT NULL,
    [2012 TV Awards & New Shows_95]                      BIGINT NULL,
    [Starz inBlack_906]                                  BIGINT NULL,
    [Lifetime Television_1360]                           BIGINT NULL,
    [Local_1008]                                         BIGINT NULL,
    [Lifetime Television_361]                            BIGINT NULL,
    [Encore_933]                                         BIGINT NULL,
    [Local_1005]                                         BIGINT NULL,
    [MC Musica Urbana_5142]                              BIGINT NULL,
    [FOX News Channel_210]                               BIGINT NULL,
    [ABC Family Channel_1179]                            BIGINT NULL,
    [NULL_1]                                             BIGINT NULL,
    [Help Channel On Demand_411]                         BIGINT NULL,
    [Estrella_3024]                                      BIGINT NULL,
    [NULL_2205]                                          BIGINT NULL,
    [Ritmoson Latino_3149]                               BIGINT NULL,
    [AT&T U-verse Shopping 4_429]                        BIGINT NULL,
    [Military History Channel_276]                       BIGINT NULL,
    [NHL Center Ice 6_788]                               BIGINT NULL,
    [NULL_4]                                             BIGINT NULL,
    [CNBC_1216]                                          BIGINT NULL,
    [Utilisima_3049]                                     BIGINT NULL,
    [Pasiones_3018]                                      BIGINT NULL,
    [Fox Sports Southwest - Dallas_1753]                 BIGINT NULL,
    [NULL_50]                                            BIGINT NULL,
    [Showtime Extreme_1858]                              BIGINT NULL,
    [Food Network Application_457]                       BIGINT NULL,
    [TV Asia_3703]                                       BIGINT NULL,
    [SOAPnet_366]                                        BIGINT NULL,
    [TVG Network_670]                                    BIGINT NULL,
    [FSN Midwest - St Louis HD_1748]                     BIGINT NULL,
    [BBC America_188]                                    BIGINT NULL,
    [Local_1063]                                         BIGINT NULL,
    [Fox Business Network_1211]                          BIGINT NULL,
    [NULL_53]                                            BIGINT NULL,
    [TMC Xtra_885]                                       BIGINT NULL,
    [SWRV_501]                                           BIGINT NULL,
    [Showtime Extreme_859]                               BIGINT NULL,
    [Local Organization_1130]                            BIGINT NULL,
    [Universal HD_1105]                                  BIGINT NULL,
    [Local_1057]                                         BIGINT NULL,
    [Showtime Showcase_1857]                             BIGINT NULL,
    [Sportsnet New York_1704]                            BIGINT NULL,
    [NULL_82]                                            BIGINT NULL,
    [Movies Coupons_199]                                 BIGINT NULL,
    [Galavision_3004]                                    BIGINT NULL,
    [Local_1031]                                         BIGINT NULL,
    [Animal Planet_253]                                  BIGINT NULL,
    [NULL_1891]                                          BIGINT NULL,
    [Animal Planet_1252]                                 BIGINT NULL,
    [CMT (Country Music Television)_526]                 BIGINT NULL,
    [Local Organization_1127]                            BIGINT NULL,
    [Local_1054]                                         BIGINT NULL,
    [Playboy TV_952]                                     BIGINT NULL,
    [USA Network_1124]                                   BIGINT NULL,
    [Nicktoons_318]                                      BIGINT NULL,
    [NULL_892]                                           BIGINT NULL,
    [Fox Soccer Plus_1653]                               BIGINT NULL,
    [MC Blues_5137]                                      BIGINT NULL,
    [NULL_105]                                           BIGINT NULL,
    [Cine Mexicano_3134]                                 BIGINT NULL,
    [AT&T Weather On Demand_227]                         BIGINT NULL,
    [NULL_85]                                            BIGINT NULL,
    [The Hub_1335]                                       BIGINT NULL,
    [Ohio News Network_233]                              BIGINT NULL,
    [TV Land_139]                                        BIGINT NULL,
    [SHORTS HD_1789]                                     BIGINT NULL,
    [mun2_193]                                           BIGINT NULL,
    [TV Polonia_3862]                                    BIGINT NULL,
    [Comedy Central_1141]                                BIGINT NULL,
    [AT&T U-verse Sports_1600]                           BIGINT NULL,
    [MoreMAX_1835]                                       BIGINT NULL,
    [Comcast SportsNet Chicago HD_1741]                  BIGINT NULL,
    [MBC America_3643]                                   BIGINT NULL,
    [NULL_9420]                                          BIGINT NULL,
    [TBN - Trinity Broadcasting Network_1560]            BIGINT NULL,
    [Smile of a Child TV_340]                            BIGINT NULL,
    [Sony Entertainment Television Asia (SET Asia)_3704] BIGINT NULL,
    [CNN Headline News_203]                              BIGINT NULL,
    [OuterMAX_1844]                                      BIGINT NULL,
    [Turner Classic Movies (TCM)_790]                    BIGINT NULL,
    [FSN South HD_1724]                                  BIGINT NULL,
    [GSN - The Network for Games_173]                    BIGINT NULL,
    [MC Kidz Only!_5127]                                 BIGINT NULL,
    [WGN America_781]                                    BIGINT NULL,
    [NULL_166]                                           BIGINT NULL,
    [National Geographic Channel_1265]                   BIGINT NULL,
    [BET (Black Entertainment Television)_155]           BIGINT NULL,
    [Longhorn Network_1609]                              BIGINT NULL,
    [CNBC Application_218]                               BIGINT NULL,
    [NBA TV_632]                                         BIGINT NULL,
    [Showtime_1852]                                      BIGINT NULL,
    [TVBe_3638]                                          BIGINT NULL,
    [Starz Cinema_908]                                   BIGINT NULL,
    [De Pelicula_3128]                                   BIGINT NULL,
    [HBO Zone_1813]                                      BIGINT NULL,
    [The Weather Channel_1225]                           BIGINT NULL,
    [ION Life_468]                                       BIGINT NULL,
    [World Harvest Television_578]                       BIGINT NULL,
    [Showtime_853]                                       BIGINT NULL,
    [NULL_18]                                            BIGINT NULL,
    [Speed Channel_1652]                                 BIGINT NULL,
    [Fox Sports Detroit_737]                             BIGINT NULL,
    [Local_1025]                                         BIGINT NULL,
    [Univision Deportes_658]                             BIGINT NULL,
    [Fox Sports South_724]                               BIGINT NULL,
    [NULL_15]                                            BIGINT NULL,
    [Local_1028]                                         BIGINT NULL,
    [Disney Channel_1302]                                BIGINT NULL,
    [MC Soundscapes_5134]                                BIGINT NULL,
    [FX Network_129]                                     BIGINT NULL,
    [H2_257]                                             BIGINT NULL,
    [MC Classic Rock_5112]                               BIGINT NULL,
    [FX Network_1128]                                    BIGINT NULL,
    [MTV Jams_508]                                       BIGINT NULL,
    [HBO2_805]                                           BIGINT NULL,
    [Local_1002]                                         BIGINT NULL,
    [Mexico 22_3022]                                     BIGINT NULL,
    [MC Singers & Swing_5138]                            BIGINT NULL,
    [ET-News_3631]                                       BIGINT NULL,
    [Current TV_189]                                     BIGINT NULL,
    [BuyIt_196]                                          BIGINT NULL,
    [MTV (Music Television)_503]                         BIGINT NULL,
    [Sun Sports_722]                                     BIGINT NULL,
    [HBO Comedy_1811]                                    BIGINT NULL,
    [TV One_157]                                         BIGINT NULL,
    [Travel Channel_254]                                 BIGINT NULL,
    [NULL_24]                                            BIGINT NULL,
    [Nat Geo WILD_266]                                   BIGINT NULL,
    [Discovery Channel_121]                              BIGINT NULL,
    [Big Ten Network_650]                                BIGINT NULL,
    [AXS TV_1106]                                        BIGINT NULL,
    [Comcast SportsNet Bay Area HD_1770]                 BIGINT NULL,
    [AT&T U-verse Movies_200]                            BIGINT NULL,
    [MC Reggae_5111]                                     BIGINT NULL,
    [NULL_47]                                            BIGINT NULL,
    [Discovery Channel_1120]                             BIGINT NULL,
    [SportSouth_729]                                     BIGINT NULL,
    [NULL_21]                                            BIGINT NULL,
    [MTV_1502]                                           BIGINT NULL,
    [MC Throwback Jamz_5107]                             BIGINT NULL,
    [My Enabled Devices DEV_9315]                        BIGINT NULL,
    [Food Network _452]                                  BIGINT NULL,
    [The Hub_335]                                        BIGINT NULL,
    [tlnovelas_3016]                                     BIGINT NULL,
    [CNBC Application_1218]                              BIGINT NULL,
    [MC Hip-Hop Classics_5106]                           BIGINT NULL,
    [MTV2_504]                                           BIGINT NULL,
    [NHL Center Ice 6_1788]                              BIGINT NULL,
    [fuse_535]                                           BIGINT NULL,
    [Latele Novela_3017]                                 BIGINT NULL,
    [BET (Black Entertainment Television)_1155]          BIGINT NULL,
    [mtvU_510]                                           BIGINT NULL,
    [qubo_3061]                                          BIGINT NULL,
    [CNNI (CNN International)_205]                       BIGINT NULL,
    [Playboy TV en Espanol_954]                          BIGINT NULL,
    [Ovation_385]                                        BIGINT NULL,
    [WGN America_1180]                                   BIGINT NULL,
    [NULL_371]                                           BIGINT NULL,
    [MSG_710]                                            BIGINT NULL,
    [TNT (Turner Network Television)_108]                BIGINT NULL,
    [VH1_1519]                                           BIGINT NULL,
    [MSG_707]                                            BIGINT NULL,
    [NHL Center Ice 5_787]                               BIGINT NULL,
    [Local Organization_1651]                            BIGINT NULL,
    [Fox Sports Southwest - San Antonio_1756]            BIGINT NULL,
    [MC Classic Country_5131]                            BIGINT NULL,
    [CNN Headline News_1203]                             BIGINT NULL,
    [Live Multiview Alternate 2_9212]                    BIGINT NULL,
    [The Weather Channel_225]                            BIGINT NULL,
    [AT&T News Multiview_201]                            BIGINT NULL,
    [Local_1012]                                         BIGINT NULL,
    [TV One_1157]                                        BIGINT NULL,
    [Local_1038]                                         BIGINT NULL,
    [NULL_5]                                             BIGINT NULL,
    [New England Sports Network_712]                     BIGINT NULL,
    [ESPN GamePlan 1_4401]                               BIGINT NULL,
    [Smithsonian Channel_118]                            BIGINT NULL,
    [The Movie Channel (TMC)_882]                        BIGINT NULL,
    [Local_1018]                                         BIGINT NULL,
    [NULL_2]                                             BIGINT NULL,
    [TBS_1113]                                           BIGINT NULL,
    [Cartoon Network_325]                                BIGINT NULL,
    [CNN en Espanol_3110]                                BIGINT NULL,
    [HBO Family_1806]                                    BIGINT NULL,
    [NULL_8]                                             BIGINT NULL,
    [MC Rock_5114]                                       BIGINT NULL,
    [FLIX_890]                                           BIGINT NULL,
    [The Tennis Channel_1660]                            BIGINT NULL,
    [Fox Sports North_744]                               BIGINT NULL,
    [Local_1015]                                         BIGINT NULL,
    [Disney Channel_302]                                 BIGINT NULL,
    [Wealth TV_1470]                                     BIGINT NULL,
    [MC 90s_5121]                                        BIGINT NULL,
    [NULL_1637]                                          BIGINT NULL,
    [Live Multiview Alternate 1_9211]                    BIGINT NULL,
    [Oxygen_368]                                         BIGINT NULL,
    [NULL_34]                                            BIGINT NULL,
    [Longhorn Network_609]                               BIGINT NULL,
    [Local_1009]                                         BIGINT NULL,
    [Lifetime Television_360]                            BIGINT NULL,
    [NULL_635]                                           BIGINT NULL,
    [BET Gospel_516]                                     BIGINT NULL,
    [NBA League Pass HD 8_2112]                          BIGINT NULL,
    [Encore Westerns_940]                                BIGINT NULL,
    [NULL_31]                                            BIGINT NULL,
    [NBA League Pass HD 7_2111]                          BIGINT NULL,
    [NULL_63]                                            BIGINT NULL,
    [TVB-V_3664]                                         BIGINT NULL,
    [NULL_37]                                            BIGINT NULL,
    [Sports Alternate 2_1692]                            BIGINT NULL,
    [MC Classical Masterpieces_5140]                     BIGINT NULL,
    [Fox Sports Southwest Alternate_754]                 BIGINT NULL,
    [NULL_60]                                            BIGINT NULL,
    [NBC Sports Network_1640]                            BIGINT NULL,
    [Starz Kids & Family_912]                            BIGINT NULL,
    [Sportsman Channel_642]                              BIGINT NULL,
    [ATMAX_846]                                          BIGINT NULL,
    [NFL Network_1630]                                   BIGINT NULL,
    [NULL_40]                                            BIGINT NULL,
    [Phoenix InfoNews_3605]                              BIGINT NULL,
    [Local_1044]                                         BIGINT NULL,
    [NULL_4500]                                          BIGINT NULL,
    [AT&T U-verse Buzz_1300]                             BIGINT NULL,
    [Sports Alternate 1_1691]                            BIGINT NULL,
    [Sports Alternate 6_1696]                            BIGINT NULL,
    [NULL_1274]                                          BIGINT NULL,
    [NULL_69]                                            BIGINT NULL,
    [MC Contemporary Christian_5132]                     BIGINT NULL,
    [Fox Business Network_211]                           BIGINT NULL,
    [HITN_3055]                                          BIGINT NULL,
    [G4_149]                                             BIGINT NULL,
    [ESPN Deportes_3113]                                 BIGINT NULL,
    [MC Romances_5146]                                   BIGINT NULL,
    [MTV Tr3s_3144]                                      BIGINT NULL,
    [Local_1041]                                         BIGINT NULL,
    [NULL_66]                                            BIGINT NULL,
    [TMC Xtra_1885]                                      BIGINT NULL,
    [ReelzChannel_799]                                   BIGINT NULL,
    [NULL_9375]                                          BIGINT NULL,
    [Local_1047]                                         BIGINT NULL,
    [FSN West HD_1772]                                   BIGINT NULL,
    [ESPN GamePlan Multiview_620]                        BIGINT NULL,
    [NHL Center Ice 3_785]                               BIGINT NULL,
    [MC Stage & Screen_5126]                             BIGINT NULL,
    [Encore Drama_942]                                   BIGINT NULL,
    [NFL RedZone HD_1629]                                BIGINT NULL,
    [NULL_1117]                                          BIGINT NULL,
    [Crime & Investigation Network_1163]                 BIGINT NULL,
    [ESPNU_1605]                                         BIGINT NULL,
    [NULL_1094]                                          BIGINT NULL,
    [Home & Garden Television (HGTV)_450]                BIGINT NULL,
    [NULL_98]                                            BIGINT NULL,
    [Cooking Channel_1456]                               BIGINT NULL,
    [OWN - Oprah Winfrey Network_1170]                   BIGINT NULL,
    [ESPN2_1606]                                         BIGINT NULL,
    [Music Choice Application_500]                       BIGINT NULL,
    [TBN Enlace USA_3078]                                BIGINT NULL,
    [YES Network_702]                                    BIGINT NULL,
    [RetroPlex_916]                                      BIGINT NULL,
    [WMAX_1842]                                          BIGINT NULL,
    [Disney XD_304]                                      BIGINT NULL,
    [PPV_104]                                            BIGINT NULL,
    [Nick2_315]                                          BIGINT NULL,
    [Showtime Too_1854]                                  BIGINT NULL,
    [Local Organization_1268]                            BIGINT NULL,
    [CBS Sports Network_1643]                            BIGINT NULL,
    [Fox Soccer Channel_654]                             BIGINT NULL,
    [FamilyNet_566]                                      BIGINT NULL,
    [Playboy TV en Espanol_3954]                         BIGINT NULL,
    [Local Organization_1267]                            BIGINT NULL,
    [NULL_7]                                             BIGINT NULL,
    [Local_1023]                                         BIGINT NULL,
    [Fox Sports Net North_745]                           BIGINT NULL,
    [Local_1020]                                         BIGINT NULL,
    [Rai Italia_3802]                                    BIGINT NULL,
    [NULL_1613]                                          BIGINT NULL,
    [Cartoon Network_1326]                               BIGINT NULL,
    [NULL_13]                                            BIGINT NULL,
    [ESPN GamePlan 5_4405]                               BIGINT NULL,
    [MC Smooth Jazz_5135]                                BIGINT NULL,
    [Nickelodeon_1314]                                   BIGINT NULL,
    [Centroamerica TV_3044]                              BIGINT NULL,
    [NULL_1636]                                          BIGINT NULL,
    [NULL_10]                                            BIGINT NULL,
    [A&E_1132]                                           BIGINT NULL,
    [Fox Sports Southwest - Dallas_753]                  BIGINT NULL,
    [Local_1017]                                         BIGINT NULL,
    [Comcast Sports Network California_1768]             BIGINT NULL,
    [NULL_16]                                            BIGINT NULL,
    [ActionMAX_837]                                      BIGINT NULL,
    [NULL_617]                                           BIGINT NULL,
    [NULL_39]                                            BIGINT NULL,
    [AMC_795]                                            BIGINT NULL,
    [HBO Comedy_811]                                     BIGINT NULL,
    [ShopNBC_424]                                        BIGINT NULL,
    [Sports Alternate 3_693]                             BIGINT NULL,
    [ThrillerMAX_1838]                                   BIGINT NULL,
    [U-verse Games Channel_93]                           BIGINT NULL,
    [Travel Channel_255]                                 BIGINT NULL,
    [ActionMAX_1836]                                     BIGINT NULL,
    [mun2_3009]                                          BIGINT NULL,
    [We (Womens Entertainment)_372]                      BIGINT NULL,
    [Home Shopping Network (HSN)_1422]                   BIGINT NULL,
    [Phoenix North America_3606]                         BIGINT NULL,
    [ABC Family Channel_178]                             BIGINT NULL,
    [Local_1055]                                         BIGINT NULL,
    [TNT (Turner Network Television)_1109]               BIGINT NULL,
    [Nat Geo WILD_1266]                                  BIGINT NULL,
    [Starz_903]                                          BIGINT NULL,
    [Sports Alternate 5_1695]                            BIGINT NULL,
    [Comcast SportsNet Bay Area_770]                     BIGINT NULL,
    [Starz_1902]                                         BIGINT NULL,
    [NULL_45]                                            BIGINT NULL,
    [Outdoor Channel_680]                                BIGINT NULL,
    [MSNBC_215]                                          BIGINT NULL,
    [NULL_646]                                           BIGINT NULL,
    [Sports Alternate 7_697]                             BIGINT NULL,
    [Investigation Discovery_1260]                       BIGINT NULL,
    [NULL_68]                                            BIGINT NULL,
    [NULL_42]                                            BIGINT NULL,
    [NHL Center Ice 2_1784]                              BIGINT NULL,
    [MC Classic Alternative_5117]                        BIGINT NULL,
    [NASA TV_264]                                        BIGINT NULL,
    [Starz Comedy_1910]                                  BIGINT NULL,
    [MTV Tr3s_507]                                       BIGINT NULL,
    [TV Chile_3032]                                      BIGINT NULL,
    [Fox Sports Net Ohio-Cincinnati_1732]                BIGINT NULL,
    [Local_1052]                                         BIGINT NULL,
    [Daystar_563]                                        BIGINT NULL,
    [The Word Network_575]                               BIGINT NULL,
    [NULL_1096]                                          BIGINT NULL,
    [Local_1046]                                         BIGINT NULL,
    [Channel One Russia_3882]                            BIGINT NULL,
    [Local_1026]                                         BIGINT NULL,
    [Showtime Beyond_860]                                BIGINT NULL,
    [Azteca America_3019]                                BIGINT NULL,
    [Starz Edge_904]                                     BIGINT NULL,
    [Fox College Sports - Atlantic_647]                  BIGINT NULL,
    [Saigon Broadcasting Television Network_3662]        BIGINT NULL,
    [Local_1049]                                         BIGINT NULL,
    [VH1_518]                                            BIGINT NULL,
    [Cinemax_833]                                        BIGINT NULL,
    [NULL_103]                                           BIGINT NULL,
    [TBS_112]                                            BIGINT NULL,
    [Sports HD Alternate 9_1699]                         BIGINT NULL,
    [QVC_1420]                                           BIGINT NULL,
    [ION_195]                                            BIGINT NULL,
    [Chiller_153]                                        BIGINT NULL,
    [NULL_1099]                                          BIGINT NULL,
    [MC Sounds of the Seasons_5133]                      BIGINT NULL,
    [FOX News Channel_1210]                              BIGINT NULL,
    [Showtime Too_1855]                                  BIGINT NULL,
    [Univision Deportes_1658]                            BIGINT NULL,
    [NULL_8001]                                          BIGINT NULL,
    [Azteca Mexico_3020]                                 BIGINT NULL,
    [Disney XD_1305]                                     BIGINT NULL,
    [CCTV-4_3603]                                        BIGINT NULL,
    [MTV India_3709]                                     BIGINT NULL,
    [MoreMAX_834]                                        BIGINT NULL,
    [Comedy Central_140]                                 BIGINT NULL,
    [Customer Notification_1100]                         BIGINT NULL,
    [MC University_5103]                                 BIGINT NULL,
    [AT&T U-verse FamilyMap App_9930]                    BIGINT NULL,
    [Destination America_1465]                           BIGINT NULL,
    [MTV Hits_509]                                       BIGINT NULL,
    [truTV_165]                                          BIGINT NULL,
    [truTV_1164]                                         BIGINT NULL,
    [MC R&B Classics_5108]                               BIGINT NULL,
    [CTI-Zhong Tian_3604]                                BIGINT NULL,
    [Lifetime Real Women_364]                            BIGINT NULL,
    [Encore_1932]                                        BIGINT NULL,
    [5StarMAX_1840]                                      BIGINT NULL,
    [Sony Movie Channel_1791]                            BIGINT NULL,
    [SportsTime Ohio_1735]                               BIGINT NULL,
    [DIY Network (Do-It-Yourself Network)_454]           BIGINT NULL,
    [U-verse Message Chanel_9920]                        BIGINT NULL,
    [HRTV_672]                                           BIGINT NULL,
    [U-verse Showcase_1800]                              BIGINT NULL,
    [Shopping Multiview_1412]                            BIGINT NULL,
    [NULL_791]                                           BIGINT NULL,
    [NULL_794]                                           BIGINT NULL,
    [Havoc TV HD_1490]                                   BIGINT NULL,
    [NBA League Pass HD 4_2108]                          BIGINT NULL,
    PRIMARY KEY CLUSTERED ([acct_id] ASC)
);

