CREATE TABLE [CLM].[acct_uvrs_feat] (
    [acct_id]                  BIGINT        NULL,
    [bill_sys_geo_id]          INT           NULL,
    [dvrc_qty]                 BIGINT        NULL,
    [hsi_actv_ind]             VARCHAR (MAX) NULL,
    [hsi_blng_eff_dt]          DATETIME      NULL,
    [hsi_blng_end_dt]          DATETIME      NULL,
    [hsi_curr_plan_cd]         VARCHAR (MAX) NULL,
    [hsi_offr_eff_dt]          DATETIME      NULL,
    [hsi_prev_plan_cd]         VARCHAR (MAX) NULL,
    [hsi_upgrd_cd]             VARCHAR (MAX) NULL,
    [ipdslam_ind]              VARCHAR (MAX) NULL,
    [iptv_actv_ind]            VARCHAR (MAX) NULL,
    [iptv_blng_eff_dt]         DATETIME      NULL,
    [iptv_blng_end_dt]         DATETIME      NULL,
    [iptv_curr_plan_cd]        VARCHAR (MAX) NULL,
    [iptv_hgh_dfnt_blt_on_ind] VARCHAR (MAX) NULL,
    [iptv_movie_pckg_ind]      VARCHAR (MAX) NULL,
    [iptv_offr_eff_dt]         DATETIME      NULL,
    [iptv_prev_plan_cd]        VARCHAR (MAX) NULL,
    [iptv_sprt_pckg_ind]       VARCHAR (MAX) NULL,
    [iptv_upgrd_cd]            VARCHAR (MAX) NULL,
    [non_dvrc_set_tp_box_qty]  BIGINT        NULL,
    [self_instld_ind]          VARCHAR (MAX) NULL,
    [tot_set_tp_box_qty]       VARCHAR (MAX) NULL,
    [voip_actv_ind]            VARCHAR (MAX) NULL,
    [voip_blng_eff_dt]         DATETIME      NULL,
    [voip_blng_end_dt]         DATETIME      NULL,
    [voip_curr_plan_cd]        VARCHAR (MAX) NULL,
    [voip_offr_eff_dt]         DATETIME      NULL,
    [voip_prev_plan_cd]        VARCHAR (MAX) NULL,
    [voip_upgrd_cd]            VARCHAR (MAX) NULL,
    [load_dt_tm]               DATETIME      NULL,
    [updt_dt_tm]               DATETIME      NULL
);

