CREATE TABLE [CLM].[imdm_acct_non_wirls_excl] (
    [acct_id]                       BIGINT        NULL,
    [bl_acct_ind]                   VARCHAR (MAX) NULL,
    [brdbnd_hotln_ind]              VARCHAR (MAX) NULL,
    [cllctn_ctrl_cd]                VARCHAR (MAX) NULL,
    [cncsn_cd]                      VARCHAR (MAX) NULL,
    [cncsn_rsn_cd]                  VARCHAR (MAX) NULL,
    [cncsn_titl]                    VARCHAR (MAX) NULL,
    [cpni_ind]                      VARCHAR (MAX) NULL,
    [cpni_pfc_cd]                   VARCHAR (MAX) NULL,
    [dep_acct_ind]                  VARCHAR (MAX) NULL,
    [empl_cncsn_ind]                VARCHAR (MAX) NULL,
    [ent_trtmnt_cd]                 VARCHAR (MAX) NULL,
    [fed_call_solicit_ind]          VARCHAR (MAX) NULL,
    [fict_acct_nbr_ind]             VARCHAR (MAX) NULL,
    [gift_rcpnt_ind]                VARCHAR (MAX) NULL,
    [imdm_call_solicit_ind]         VARCHAR (MAX) NULL,
    [imdm_knck_solicit_ind]         VARCHAR (MAX) NULL,
    [imdm_mail_solicit_ind]         VARCHAR (MAX) NULL,
    [lfln_acct_ind]                 VARCHAR (MAX) NULL,
    [locl_crdt_optn_ind]            VARCHAR (MAX) NULL,
    [non_lstd_ind]                  VARCHAR (MAX) NULL,
    [non_pubtn_ind]                 VARCHAR (MAX) NULL,
    [non_pubtn_wth_out_foll_up_ind] VARCHAR (MAX) NULL,
    [oca_ind]                       VARCHAR (MAX) NULL,
    [pmt_bhvr_scr_nbr]              BIGINT        NULL,
    [pmt_elgbly_ind]                VARCHAR (MAX) NULL,
    [mdncn_call_solicit_ind]        VARCHAR (MAX) NULL,
    [prepd_acct_ind]                VARCHAR (MAX) NULL,
    [prepd_lfln_acct_ind]           VARCHAR (MAX) NULL,
    [spec_blng_arng_ind]            VARCHAR (MAX) NULL,
    [sprt_acct_ind]                 VARCHAR (MAX) NULL,
    [src_call_solicit_ind]          VARCHAR (MAX) NULL,
    [src_mail_solicit_ind]          VARCHAR (MAX) NULL,
    [st_call_solicit_ind]           VARCHAR (MAX) NULL,
    [st_call_solicit_st_cd]         VARCHAR (MAX) NULL,
    [telco_hotln_ind]               VARCHAR (MAX) NULL,
    [trtmnt_cd]                     VARCHAR (MAX) NULL,
    [trtmnt_ind]                    VARCHAR (MAX) NULL,
    [tty_acct_ind]                  VARCHAR (MAX) NULL,
    [vld_blng_addr_ind]             VARCHAR (MAX) NULL,
    [wirls_hotln_ind]               VARCHAR (MAX) NULL,
    [wirls_phn_call_solicit_ind]    VARCHAR (MAX) NULL,
    [load_dt_tm]                    DATETIME      NULL,
    [updt_dt_tm]                    DATETIME      NULL
);

