CREATE TABLE [sandbox].[imdm_cust_loc_UVsales_20140226_20140430] (
    [CUSTOMER LOCATION IDENTIFIER]        BIGINT      NULL,
    [SOURCE CUSTOMER LOCATION IDENTIFIER] BIGINT      NULL,
    [U-VERSE ORIGINAL SERVICE DATE]       DATETIME    NULL,
    [U-VERSE IPTV SUBSCRIPTION INDICATOR] VARCHAR (1) NULL,
    [U-VERSE VOIP SUBSCRIPTION INDICATOR] VARCHAR (1) NULL,
    [U-VERSE HSI SUBSCRIPTION INDICATOR]  VARCHAR (1) NULL
);

