CREATE TABLE [sandbox].[TEST_camplist] (
    [ReportCycle_YYYYWW]             INT           NULL,
    [Report_year]                    INT           NULL,
    [business_unit_name]             VARCHAR (25)  NULL,
    [JobNumber]                      VARCHAR (100) NULL,
    [Tactic_id]                      NUMERIC (11)  NULL,
    [Aprimo_ID]                      VARCHAR (10)  NULL,
    [Project_ID]                     NUMERIC (11)  NULL,
    [ParentID]                       NUMERIC (12)  NULL,
    [eCRW_Cell_ID]                   INT           NULL,
    [AlamoID]                        INT           NULL,
    [First_Drop_Date]                DATETIME      NULL,
    [Last_Drop_Date]                 DATETIME      NULL,
    [In_Home_Date]                   DATETIME      NULL,
    [Start_Date]                     DATETIME      NULL,
    [End_Date_Traditional]           DATETIME      NULL,
    [eCRW_Project_Name]              VARCHAR (250) NULL,
    [Campaign_Name]                  VARCHAR (250) NULL,
    [Campaign_Description]           VARCHAR (250) NULL,
    [Campaign_Parent_Name]           VARCHAR (250) NULL,
    [ecrw_cell_title]                VARCHAR (250) NULL,
    [cell_description]               VARCHAR (250) NULL,
    [Program]                        VARCHAR (50)  NULL,
    [Media_code]                     VARCHAR (50)  NULL,
    [Media_code_long]                VARCHAR (50)  NULL,
    [Media_Excel]                    VARCHAR (50)  NULL,
    [Media_MC]                       VARCHAR (50)  NULL,
    [Media_Type]                     VARCHAR (50)  NULL,
    [Media_Display]                  VARCHAR (50)  NULL,
    [Media_Scorecard]                VARCHAR (50)  NULL,
    [Product_code]                   VARCHAR (50)  NULL,
    [Product_Excel]                  VARCHAR (50)  NULL,
    [Product_MC]                     VARCHAR (50)  NULL,
    [Product_Display]                VARCHAR (50)  NULL,
    [Region_code]                    VARCHAR (50)  NULL,
    [Region_Excel]                   VARCHAR (50)  NULL,
    [Region_MC]                      VARCHAR (50)  NULL,
    [Region_Type]                    VARCHAR (50)  NULL,
    [Region_Display]                 VARCHAR (50)  NULL,
    [Campaign_Type]                  VARCHAR (50)  NULL,
    [Campaign_SubType]               VARCHAR (50)  NULL,
    [CustomerGroup]                  VARCHAR (50)  NULL,
    [ProjectCategory]                VARCHAR (50)  NULL,
    [Retention_YN]                   VARCHAR (50)  NULL,
    [Vendor]                         VARCHAR (50)  NULL,
    [Date_CRW_Created]               DATETIME      NULL,
    [Date_CRW_Modified]              DATETIME      NULL,
    [crw_call_resp_rate]             FLOAT (53)    NULL,
    [crw_click_resp_rate]            FLOAT (53)    NULL,
    [crw_sales_resp_rate]            FLOAT (53)    NULL,
    [Toll_Free_Numbers]              VARCHAR (MAX) NULL,
    [URL_List]                       VARCHAR (MAX) NULL,
    [status_name]                    VARCHAR (50)  NULL,
    [ExcludeFromScorecard]           VARCHAR (50)  NULL,
    [Flag_Include_Campaign_Report]   VARCHAR (50)  NULL,
    [Flag_Include_Campaign_Report_i] VARCHAR (50)  NULL,
    [Flag_Include_Stim_Report]       VARCHAR (50)  NULL,
    [Flag_Include_Summary_Report]    VARCHAR (50)  NULL,
    [Flag_Include_Sales_Report]      VARCHAR (1)   NULL,
    [Flag_IPDSLAM]                   VARCHAR (1)   NULL,
    [Response_Curve_Calls]           VARCHAR (50)  NULL,
    [Response_Curve_Clicks]          VARCHAR (50)  NULL,
    [Response_Curve_TS]              VARCHAR (50)  NULL,
    [Response_Curve_ON]              VARCHAR (50)  NULL,
    [Conv_Rate_ID]                   VARCHAR (50)  NULL,
    [CRW_STRAT_Call_Conv_Rate]       FLOAT (53)    NULL,
    [CRW_STRAT_Click_Conv_Rate]      FLOAT (53)    NULL,
    [CRW_UVRS_Call_Conv_Rate]        FLOAT (53)    NULL,
    [CRW_UVRS_Click_Conv_Rate]       FLOAT (53)    NULL,
    [CTD_TFN_SharedNumbers]          NUMERIC (11)  NULL,
    [CTD_TFN_SharedCampaigns]        NUMERIC (11)  NULL,
    [CTD_TFN_DaysShared]             NUMERIC (11)  NULL,
    [CTD_TFN_QuantityShared]         FLOAT (53)    NULL,
    [CTD_URL_SharedURLs]             NUMERIC (11)  NULL,
    [CTD_URL_SharedCampaigns]        NUMERIC (12)  NULL,
    [CTD_URL_DaysShared]             NUMERIC (12)  NULL,
    [CTD_URL_QuantityShared]         FLOAT (53)    NULL,
    [CTD_Quantity]                   NUMERIC (20)  NULL,
    [CTD_Budget]                     FLOAT (53)    NULL,
    [Source_Campaign_Info]           VARCHAR (50)  NULL,
    [Source_CTD_Quantity]            VARCHAR (50)  NULL,
    [Source_CTD_Budget]              VARCHAR (50)  NULL,
    [Source_ITP_Quantity]            VARCHAR (50)  NULL,
    [Source_ITP_Budget]              VARCHAR (50)  NULL,
    [Source_Dir_Calls]               VARCHAR (50)  NULL,
    [Source_Dir_Clicks]              VARCHAR (50)  NULL,
    [Source_Dir_QRScans]             VARCHAR (50)  NULL,
    [Source_Dir_TS]                  VARCHAR (50)  NULL,
    [Source_Dir_ON]                  VARCHAR (50)  NULL,
    [Source_MC_Sales]                VARCHAR (50)  NULL,
    [Source_MC_Calls]                VARCHAR (50)  NULL,
    [Source_MC_Clicks]               VARCHAR (50)  NULL,
    [Source_MC_QRScans]              VARCHAR (50)  NULL,
    [Source_LTV_Values]              VARCHAR (50)  NULL,
    [Source_ARP_Values]              VARCHAR (50)  NULL,
    [Source_Goal_Quantity]           VARCHAR (50)  NULL,
    [Source_Goal_Dir_Calls]          VARCHAR (50)  NULL,
    [Source_Goal_Dir_Clicks]         VARCHAR (50)  NULL,
    [Source_Goal_Dir_Sales_TS]       VARCHAR (50)  NULL,
    [Source_Goal_Dir_Sales_ON]       VARCHAR (50)  NULL,
    [ecrw_top]                       VARCHAR (50)  NULL,
    [ecrw_lob]                       VARCHAR (50)  NULL,
    [ecrw_segment]                   VARCHAR (50)  NULL,
    [ecrw_segment_name]              VARCHAR (50)  NULL,
    [ecrw_channel_name]              VARCHAR (50)  NULL,
    [ecrw_classification_name]       VARCHAR (50)  NULL,
    [program_paid_outside]           VARCHAR (1)   NULL,
    [TimeStamp_Modified]             DATETIME      NULL,
    [End_date_max]                   INT           NULL
);

