CREATE TABLE [sandbox].[TVSales_20131101_20140214] (
    [CUSTOMER LOCATION IDENTIFIER]  BIGINT       NULL,
    [ACCOUNT IDENTIFIER]            BIGINT       NULL,
    [U-VERSE ORIGINAL SERVICE DATE] DATETIME     NULL,
    [IPTV CURRENT PLAN CODE]        VARCHAR (50) NULL,
    [IPTV BILLING EFFECTIVE DATE]   DATETIME     NULL,
    [SOURCE CREATION DATE]          DATETIME     NULL,
    [ACCOUNT NUMBER]                BIGINT       NULL
);

